### ISSUE TITLE
Sustaining the Future: Efficiency Strategies for Nostr Relays Panel

### ISSUE THREAD

**Issue by miketwenty1** [nostrworld/nostriga#1]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
- Is the model of clients publishing and therefore duplicating data _O(n)_ amongst the server relays the future of relays?
- What are the usecases for short, medium, and long term storage for the Nostr architecture design?
- Will there always be an idea on Nostr of a long term persistent "free lunch" relay? or will these eventually need to be monetized in some way?
### What would an attendee learn from this talk?
- Nostr design decisions / tradeoffs.

### Moderator
- @miketwenty1 (myself as moderator)

### About the panelist
- @arcbtc (o.g.)
- @jb55 (damus)
- ~@v0l (snort.social)~
- @rabble (nos.social)

### Social Links
- https://primal.net/p/npub1gcxzte5zlkncx26j68ez60fzkvtkm9e0vrwdcvsjakxf9mu9qewqlfnj5z
- https://primal.net/p/npub1v0lxxxxutpvrelsksy8cdhgfux9l6a42hsj2qzquu2zk7vc9qnkszrqj49
- https://primal.net/p/npub107jk7htfv243u0x5ynn43scq9wrxtaasmrwwa8lfu2ydwag6cx2quqncxg
- https://primal.net/p/npub137c5pd8gmhhe0njtsgwjgunc5xjr2vmzvglkgqs5sjeh972gqqxqjak37w
-
https://rabble.nos.social 

# Panel Discussion Details
### Length of the panel discussion
30 minutes

### Preferred Day/Time Slot 
Whatever

**Comment by miketwenty1** [comment]
Hey I was told I needed to fill this panel, I wouldn't mind moderating. Would @arcbtc @jb55 be interested as panelist?

**Comment by miketwenty1** [comment]
I got @v0l, @arcbtc and @jb55 to say they will be on the panel, but trying to get them to ack here.

**Comment by jb55** [comment]
ack

**Comment by arcbtc** [comment]
Ack 🔥🔥🔥

**Comment by miketwenty1** [comment]
Adding @rabble to this panel as he has been deep with cost savings and relay services.

**Comment by exfrog** [comment]
Please remind foh av so they get lower thirds correct

**Comment by miketwenty1** [comment]
@v0l dropping, so im guessing this is no problem @exfrog
