### ISSUE TITLE
Turning the screws: How double ratchet encryption works on Nostr

### ISSUE THREAD

**Issue by erskingardner** [nostrworld/nostriga#10]
# Description

### What is this talk about? Give us as many details as possible. 

In this talk I'll describe what it takes to create private communications between two or more people, and talk about why hiding metadata is just as important as hiding the content of the messages. Given this is after the fireside talk that will cover the past and present of DMs and Group chats, I'll dive right in in this talk to cover my earlier NIP-104 proposal that adapted the signal protocol to Nostr and why that has now been closed in favor of implementing the new MLS protocol. 

We'll talk about the details future and post compromise secrecy and how double ratchet and ratchet trees work. Then we'll talk about how we plan to protect user metadata across the nostr network while implementing MLS in clients. And finally, cover some of the trade offs inherent in building highly secure private chats.

### What would an attendee learn from this talk?

Why Nostr is different from other platforms out there when it comes to private communications and how we've been able to overcome limitations to build a truly decentralized, yet highly secure method of encrypting DMs and group conversations on Nostr. They'll also learn more about the other schemes that have been tried over the last year and the trade offs inherent in each method of encrypting messages.

### Is there anything folks should read up on before they attend this talk?

There are several NIPs that describe the various specs for encrypting and obfuscating content on Nostr. Having an understanding of the signal protocol or MLS protocol at a high level is also helpful. There are two great videos on the topic that take just a few minutes to watch: 

- [Signal Double Ratchet Algo](https://youtu.be/7uEeE3TUqmU?si=yUhcQpJw5_Ag8R48)
- [MLS](https://youtu.be/FESp2LHd42U?si=sbeQBN6MDL7TEl6S)

### Relevant Links

[NIP-04: Early DMs](https://github.com/nostr-protocol/nips/blob/master/04.md)
[NIP-17: Latest recommended DMs](https://github.com/nostr-protocol/nips/blob/master/17.md)
[NIP-44: New method of encrypting content between two parties](https://github.com/nostr-protocol/nips/blob/master/44.md)
[NIP-59: Gift-wrapping of events](https://github.com/nostr-protocol/nips/blob/master/59.md)
[NIP-104: Double ratchet E2EE DMs PR](https://github.com/nostr-protocol/nips/pull/1206) (now closed in favor of upcoming MLS proposal)

# About the Speaker

Jeff Gardner has been building software and working in high-growth startups for more than 15 years and working full-time on Nostr for 18 months. Working with the support of an OpenSats grant, he’s built Nostr.how, Listr, Ostrich.work, Ontolo, and most recently has written the NIP for E2EE Direct Messages on Nostr. He also is a significant contributor to NDK, the Nostr Development Kit.

### Social Links
https://primal.net/jeffg
https://github.com/erskingardner
https://x.com/erskingardner

# Talk Details

### Length of Talk
45min

### Preferred Day/Time Slot 
Whatever works.

**Comment by islandbitcoin** [comment]
Wanna make this a fireside chat with @abhay-raizada ?

Abhay is currently working on getting secure nostr DMs working in [Flash](https://github.com/lnflash/whatcha-ma-call-it), and also working on a [NIP using gift wraps](https://github.com/nostr-protocol/nips/pull/1190)

or maybe a separate fireside chat after your keynote...

**Comment by erskingardner** [comment]
Chatted with @islandbitcoin and @abhay-raizada about this. Going to edit this talk (which will be more about MLS, not signal) and then create a new fireside chat / panel to talk about history and tradeoffs of the various DM and group chat NIPs.
