### ISSUE TITLE
Talk: Beyond social media ⚡🔥

### ISSUE THREAD

**Issue by arcbtc** [nostrworld/nostriga#11]
### What is this talk about? Give us as many details as possible. 
The paradigm of smart client dumber server and access to raw public key crypto means we can replace a LOT of things with nostr native solutions, and Nostr actually makes sense as a platform

In the talk I will be electrocuted every time someone zaps me (using the Zap switch project), once zaps reach a certain threshold will make a fireball from a fireball machine. 
(all proceeds to #freeassange)

While being electrocuted and set on fire I will demo/talk about:
* How far Nostr market has come, and implications of p2p commerce.
* The amazing things you can do with Nostr IoT, how incredibly easy it is to use, why Nostr IoT is important for avoiding surveillance and all the horrid T&Cs in IoT solutions.
* Hardware Nsec bunkers, and their implications moving into a world of public-key crypto (when captchas and passwords become too insane to remember).
* Nostr Uber and Sex work.
* All these goofy experiments actually have rather profound real world implications.
* Will unveil some other stuff we have not built and thought about yet.

### What would an attendee learn from this talk?
Nostr is pronounced nos-da, and that electrocuting people on stage while trying to demo things is good honest fun.

### Is there anything folks should read up on before they attend this talk?
No. Unlearn everything beforehand in fact.

### Relevant Links
https://github.com/lnbits/nostr-zap-lamp
Will add more later

# About the Speaker
### Social Links
Nostr: [ben@nostr.com](https://njump.me/ben@nostr.com)
Github: @arcbtc
Twitter: My twitter profile will be dead by then or I will eat my own dick.
Website: https://nostr.com/nostr.org

# Talk Details
### Length of Talk: 
10minis - ∞mins
### Preferred Day/Time Slot: 
Any

[![wear purple or die trying](https://i.imgur.com/VTmp3FI.png)](https://www.youtube.com/watch?v=qCBVjNEvQ7o?si=Jud1xBeqR0Ar-8GR)

**Comment by rockstardev** [comment]
Will there be a minimum sats for zapping or literally any amount (1 sat) will still result in a zap?

**Comment by itstomekk** [comment]
how much one needs to zap to electrocut @rockstardev ?
does sat amount dictate the voltage?
