### ISSUE TITLE
"Nostr Native" vs "Nostr Integrated", an Alternative Approach to Design Nostr Applications

### ISSUE THREAD

**Issue by waterblower** [nostrworld/nostriga#13]
# Description
### What is this talk about? Give us as many details as possible. 
Historically, nostr development has been splited to client development and relay (server) development and the idea is that 

1. If clients and servers are developed by different people/teams and they all follow the same protocol, the decentralization is strengthened.
2. If client developers start to also develop its own relays/servers, it weakens the decentralizaiton.

After 1 year of pure client development, I declare that No.2 argument is absolutely wrong and No.1 argument is questionable.

Wether a practice strengthens or weakens the decentralizaiton, we need to understand that there are at least 

__3 dimensions of decentralizaiton__:

1. Decentralization of software vendoring / features
 - This is the fact that Nostr has many different clients to choose from, so that a user can switch applications either because they start to dislike one or they want to use features that don't exist in one.

 - For example, I don't write blogs on Damus, I use [habla](habla.news) or [highligheter](highligher.com) to write. I mainly use [blowater](blowater.app) to chat. I mainly use Damus and [coracle](coracle.social) to browse social media.

2. Decentralization of data
- This is the fact that there are many different relays/servers to choose from so that data is not stored/operated by a single person/team/organization
- For example, there are [damus relay](relay.damus.io), [nos](nos.lol), [yabu.me](yabu.me) and more

3. Decentralization of users
- Nostr users are real people. They live in different regions of the world, with different cultures. When we design softwares, we have to respect this reality. Users of different languages and cultures will use different software. 
- For example, Japanese users tend to use the relay yabu.me and clients developed by Japanese developers. This choice is similar to No.1, but not from a functionality angle, but from a design/culture angle.

With this undersatnding, let's go back to the original 2 arguments and we will realize that separating client development and relay development does not help these 3 dimentions fundementally and sometimes it can harm them.

Remember, __user experience is the most important thing. Strengthening decentralization should never sacrifice user experience__.

#### [Geyser](https://geyser.fund/)
Geyser is an independent system that works without Nostr. It has its own frontend, backend and account system. However, it integrates with Nostr. Each geyser project is also a nostr npub so that activities regarding this project can be seen on Nostr. This is a brilliant design that
1. keeps geyser decoupled from Nostr NIPs so that its data format and overall architecture can envolve independently
2. integrate parts that make sense to participate in Nostr so that Nostr serves as a discoverability and social layer.

#### [Alby](https://getalby.com/)
Alby is a lightning wallet. But it's also a Nostr NIP-07 extension. In the same way, Alby has its own system and only integrate with Nostr in parts that make its product better.

#### [Zap.stream](https://zap.stream)
zap.stream is a streaming service. It stores videos in its own backend and uses Nostr at its account system, comment system and micro tipping (zap) system.

### Case studies: Nostr Native Applications
In the contrary, Nostr native applications builds everything on top of Nostr relays and minimize the use of external backend systems and avoid building its own backends. Pretty much all Nostr clients fall into this category.

What are problems with the Nostr Native approach?

The Nostr event format and relay API is originally designed for social media, especially Twitter style short message. It is not designed for all kinds of applications. Binary data can't be stored with JSON so that despite there are tens of clients and 1000+ relays to choose from, there are fewer than 5 good image/multi-media servers out there.

__The reverse barrel effect__
The decentralization level of a big system is dictated by the decentralization level of the most complex sub-system. Multi-media system is more complex than textual systems, so that the decentralization level of Nostr is dictated by the decentralization level of media servers.

Also, because nostr events are not the best format for many kinds of features, client developers have to come up with inefficient way to use Nostr events as the only means of communication and storage format. This actually slows client developer down. Just because client developers don't write backend code does not mean that they move faster.

### Developing both the client and the server is better
I claim that designing and implementing both the client and the server actually makes the client developer faster because they can only design and implement the parts they need and don't worry about compatibility issues with other Nostr applications. They only need to integrate the parts that actually benefits from Nostr.

This aprroach also strengthen the 3 dimensions of decentralization

1. Decentralization of software vendoring / features
 - Now we not only have more clients to use, but also more servers to choose 

2. Decentralization of data
- By implementing servers, data are further decentralized
- If servers are standalone softwares, other people can operate this server, not exclusive to the server implementer.

3. Decentralization of users
- Because the client is its own independent system now, it has the ability to offer very unique features that are hard to find in pure client software. Better user experience.

### What would an attendee learn from this talk?
Nostr Native application is a __dalse proposition__. We should design good independent software that integrates with Nostr.

### Is there anything folks should read up on before they attend this talk?
No, I will make the talk easy to follow

### Relevant Links

# About the Speaker
I am Water Blower, a professional software engineer who used to work for "VC big tech" and now am learning and inspired to become an independent software engineer and an independent person who might eventually inspire other people to become independent and take responsibilities for their lives.

I love workout, food, music and sleep.

### Social Links
Nostr: npub1dww6jgxykmkt7tqjqx985tg58dxlm7v83sa743578xa4j7zpe3hql6pdnf
The client I am working on: https://blowater.app
The relay/server I am working on: https://github.com/BlowaterNostr/relayed

# Talk Details
### Length of Talk
30 minutes
### Preferred Day/Time Slot 
Afternoon

**Comment by vicariousdrama** [comment]
I can't make it to Nostriga, but I like this idea. I think we should promote more integrating existing applications/services to leverage nostr where it makes sense.  This is part of the ethos behind Corny Chat, which took an existing open source application, and began adding nostr enabled elements to it (login, verification, zaps, lists of links and slides, profiles, note viewing). 

That said, if building an application from scratch, it's certainly worth considering a more nostr centric/native approach for common app features.

Have you considered a portion of your talk/presentation to be devoted to some of the high level tradeoffs for apps using relays for data storage or general comms, and whether those relays are under central control or not? A big part of the appeal of nostr for new apps is that the storage can be offloaded, and even basic lookups (via filters) making for simple apps to be deliverable in static web pages.

**Comment by waterblower** [comment]
@vicariousdrama 
> Have you considered a portion of your talk/presentation to be devoted to some of the high level tradeoffs for apps using relays for data storage or general comms, and whether those relays are under central control or not?

Yes, I want to discuss it

**Comment by waterblower** [comment]
@rockstardev Sorry to this last minute notice. I can't make it to the conference this time. Can we cancel this talk?
