### ISSUE TITLE
RIP Global, web-of-trust as the ONLY valid entry-point to the internet

### ISSUE THREAD

**Issue by pablof7z** [nostrworld/nostriga#14]
# Description
Exploration about the transformative potential of Nostr's Web of Trust (WoT) in reshaping how users navigate and verify information on the internet.

With the proliferation of AI technologies and the increasing challenges of digital impersonation, establishing trust and authenticity online has never been more crucial.

The panel will delve into the concept of using Nostr's WoT as a foundational layer for internet interactions, focusing on its implications for content verification, social networking, and digital identity.

Some keypoints we'll touch on are how, in an internet where "identity" (loosely defined) is everything, where the sea of information makes naive content consumption unworkable, a portable, unsiloed identity is desperately needed.

# About the panelist
- @pablof7z
- stuart bowman
- hzrd 
- Moderator: @cypherperro

# Panel Discussion Details
Duration: 40 min

**Comment by alltheseas** [comment]
Is @fr4nzap joining this talk?

**Comment by miketwenty1** [comment]
@pablof7z this talk has been accepted. Please try to finalize panelist and moderator. If panelist have a Github account, please tag them here.

**Comment by rockstardev** [comment]
@pablof7z another gentle bump to take a look at it per @miketwenty1 message

**Comment by pablof7z** [comment]
@pippellia-btc too in the panel

**Comment by pippellia-btc** [comment]
really? That would be soo cool. Totally down for it

**Comment by pablof7z** [comment]
> really? That would be soo cool. Totally down for it

That's why I asked for your GitHub handle a couple weeks ago 😅

**Comment by lovvtide** [comment]
> Is @fr4nzap joining this talk?

Hope so!

**Comment by exfrog** [comment]
How about ODELL moderates this?

**Comment by exfrog** [comment]
> How about ODELL moderates this? 
If he can make it in time!

**Comment by alltheseas** [comment]
This is going to be a world record: 2 moderators, and 8 panelists. 

Will there be an MMA fence, with say, two mics?

😂

😘
