### ISSUE TITLE
Make Nostr interoperability Great: nostrability and nostrCI workshop for devs

### ISSUE THREAD

**Issue by alltheseas** [nostrworld/nostriga#15]
# Description
### What is this workshop about? 

[Nostrability](https://github.com/nostrability) is the practical study of how well nostr apps work together. [nostrCI](https://github.com/nostrCI) is the automated assessment of the interactions between nostr apps. This is a technical workshop for nostr app devs, and CI/devops experts.

### What would an attendee learn from this workshop?
This is a technical focused workshop for devs to propose feedback and best practices on nostrability. Workshop will serve as a brainstorming & product definition workshop for automated nostr app interaction testing in nostrCI. 

An ideal outcome is:
1) defining what the nostrCI product does (on day one)

2) defining a "job description" for a dedicated full time nostrCI/devops eng

3) nostrability real world process improvements

bonus points: resolution, and/or follow up to [currently open nostrability issues](https://github.com/nostrability/nostrability/issues)

### Is there anything attendees should read up on before they attend this talk?

See nostrability, and nostrCI repos. 

### Is there anything attendees should set up before the workshop?

No. You can

1. watch [how nostr wins](https://youtu.be/qTixqS-W1yo?feature=shared) by @pablof7z 

2. watch [nostrability and nostrCI overview](https://www.youtube.com/watch?v=I3Qld_HXQuM)

https://slides.com/alltheseas/nostrability

# About the Speaker

### Social Links

npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5
Github.com/alltheseas

# Workshop Details
### Length of workshop
30 minutes - 2 hours

### Preferred Day/Time Slot

**Comment by rockstardev** [comment]
I must say that I am impressed by your initiative to document [issues on Nostr](https://github.com/nostrability/nostrability/issues).

![image](https://github.com/nostrworld/nostriga/assets/5191402/ff791da9-68e1-4f27-9348-418e98b20987)

Really hoping this talk will raise awareness for nostrCI.

**Comment by alltheseas** [comment]
https://github.com/nostrworld/nostriga/issues/32 is a specific nostrability issue workshop - gossip

**Comment by alltheseas** [comment]
@seankibler 
@dskvr
@miketwenty1
@nourspace yall ready to talk nostrCI?

**Comment by miketwenty1** [comment]
@alltheseas i was born ready

**Comment by alltheseas** [comment]
template for CI contributor JD https://github.com/nostrCI/nostrCI/issues/4
