### ISSUE TITLE
Communities on Nostr with Ditto

### ISSUE THREAD

**Issue by alexgleason** [nostrworld/nostriga#16]
# Description
### What is this talk about? Give us as many details as possible. 
**Building Communities on Nostr with Ditto** 
Nostr currently lacks a meaningful tool for communities to set their own standards for content and behavior, while still maintaining the full spirit and freedom of the protocol. Ditto provides a solution by allowing users to opt into curated communities while still remaining connected to the larger Nostr network and enjoying all the benefits of an open protocol.

Ditto is a self-hosted server featuring a community-centered Nostr relay with a built-in UI. Each Ditto server hosts it's own community of users, tied together by common identity but free to take their keys and leave at any time. Ditto offers robust moderation tools at both the server and user level so that both communities and the individuals within them can craft their ideal experience on Nostr.

### What would an attendee learn from this talk?
- Why building communities on Nostr is important to the long-term growth of the network
- What is Ditto
- How to create or join a Nostr community on Ditto
- Content moderation on Ditto
- How Ditto interoperates with hundreds of existing apps

### Is there anything folks should read up on before they attend this talk?
The audience should already have a 101-level understanding of Nostr and how to use it. 

### Relevant Links
- [https://soapbox.pub/ditto/](https://soapbox.pub/ditto/)
- [https://soapbox.pub/blog/curated-communities-with-ditto/](https://soapbox.pub/blog/curated-communities-with-ditto/ 
)

# About the Speaker
### Social Links
[Nostr](https://njump.me/nprofile1qqs8nsk2uy2w529fs8n4tx60u7z553e4yx5dy2nxhw4elgjgawpqlaspz4mhxue69uhhyetvv9ujumt0wd68ytnsw43q4hag5n)
[Github](https://gitlab.com/soapbox-pub/) 
[Twitter](https://twitter.com/SoapboxTech)
[Website](https://alexgleason.me/)

# Talk Details
### Length of Talk
30-45 mins

### Preferred Day/Time Slot 
Any

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by rockstardev** [comment]
@alexgleason, one question about Ditto I couldn't find answer to: do notes posted within still propagate and remain visible to the external network? To me, the biggest value of close-knit communities is in their ability to support each other (likes / reposts / etc) to push their discussions / interests outwards.

**Comment by alexgleason** [comment]
@rockstardev Absolutely. The goal is to do what Mastodon did well with communities, but with the freedom of Nostr and none of the downsides.

Each Ditto server has a relay exposed at `/relay` (eg https://gleasonator.dev/relay). Users can choose which relays they want to broadcast to, and admins also get a screen similar to this.

![image](https://github.com/nostrworld/nostriga/assets/3639540/217bcf02-d0cf-43d2-9c03-6a45a8eb6741)

The way we get content is actually similar to Primal (with a [firehose](https://docs.soapbox.pub/ditto/internals/firehose/)) but a goal is to prune old content to keep the database small and affordable to self-hosters.

Also, Ditto implements the entire Mastodon client-server API (eg https://gleasonator.dev/api/v1/instance) by doing a [crazy NIP-46 thing](https://docs.soapbox.pub/ditto/signing/), so it's actually possible to use nsecbunker to sign in with dozens of [native Mastodon apps](https://joinmastodon.org/apps). This will blow your mind. :joy: 

EDIT: Oh, and the way communities are delineated is by NIP-05 domain name. Ditto grants each user a name on the domain. And you can view feeds of any domain, eg: https://gleasonator.dev/timeline/nostrplebs.com

**Comment by alexgleason** [comment]
What can I do to get this one approved? I'm going to start working on the presentation now. And I'm bringing my clan to the conference. I promise it will be very entertaining.

**Comment by fiatjaf** [comment]
Are you going to have a Pokémon in your slides?

**Comment by alexgleason** [comment]
I would never violate a corporation's intellectual property like that.

**Comment by gsovereignty** [comment]
Will there be gleasonator branded swag for attendees?
