### ISSUE TITLE
Workshop: Join Hen House! The first women-only Nostr relay.

### ISSUE THREAD

**Issue by marykatefain** [nostrworld/nostriga#17]
# Description
### What is this workshop about? Provide as many details as possible. 
**Women-only: Join Hen House! The first women-only Nostr relay.**
In this workshop, women of Nostr can learn how to sign up for Hen House, a women-only community on Nostr made with Ditto. 

### What would an attendee learn from this workshop?
- What is Hen House?
- How does Hen House create a curated community for women on Nostr? 
- How to join and use Hen House with your existing NPUB, or how to create a new account on Hen House
- Open discussion of community standards and expectations
- Make friends with other ladies of Nostr!

### Is there anything attendees should read up on before they attend this talk?
No, this will be accessible to brand-new Nostr users

### Relevant Links
[https://henhouse.social/](https://henhouse.social/)

# About the Speaker
M.K. Fain is the creator of the largest women-first community on decentralized social media: Spinster.xyz. 

### Social Links
[Nostr](https://njump.me/npub1jvnpg4c6ljadf5t6ry0w9q0rnm4mksde87kglkrc993z46c39axsgq89sc)
[Github](https://gitlab.com/marykatefain) 
[Twitter](https://twitter.com/mkay_fain)
[Website](https://spinster.xyz/@mk)

# Workshop Details
### Length of workshop
30 - 45 mins

### Preferred Day/Time Slot 
Any time is fine but, if possible it would be great to schedule after the talk on Ditto (if accepted) because that will help attendees have a better baseline understanding.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by rockstardev** [comment]
Related to https://github.com/nostrworld/nostriga/issues/16

**Comment by sexylibrarian** [comment]
As a happy Hen House relay user, I would like to see wider adoption of its use, because it is a fantastic product.
