### ISSUE TITLE
Nostr 101 Track - Nostr for Beginners - Various Workshops

### ISSUE THREAD

**Issue by derekross** [nostrworld/nostriga#19]
# Description
### What is this workshop about? Provide as many details as possible. 
I would like to host and participate in a "Nostr 101 Track" at Nostriga. Unfortunately at this time, Nostr is still very technical. We haven't reached a point with Nostr where the technical layer just falls into the background. Education here is key for continued user adoption and growth. These talks and workshops would consist of multiple talks by a variety of people. These series of talks and workshops should be considered for Nostr beginners looking to learn about what Nostr is, various terminologies, but most importantly, focusing on all of the various "Other Stuff" applications and micro-services that showcase Nostr's entire ecosystem.
### What would an attendee learn from this workshop?
In the past, I've used the #HOWDONOSTR hashtag across Nostr to showcase various aspects of "How to use Nostr". This Nostr 101 Track is essentially an extension of that hashtag, focusing on Nostr education.

While I don't want these talks to be overly technical, I still feel it is important to talk about some technical aspects of Nostr such as public and private keys, self custody of those keys, relay configuration, choosing relays, paid/free relays, and zaps and wallets/clients. The end result would be attendees having an understanding about the technical layer and terminology of Nostr.

Next, I'd like to have a talk or workshop discussing what makes Nostr different, focusing on ownership of user data, and portability of your social graph across different clients. This talk or workshop would then dive into running your own relay, showcasing one or two options and implementations. The end result for attendees would be the ability to go home and spin up their own relay so that they can be sovereign over their own data.

The next workshop should begin the focus on "Other Stuff" applications and how to access them. Showing various web browser extensions and nsecBunker alternatives. This is the largest technical hurdle when accessing "Other Stuff" on the web. Signing into these applications is HARD! The goal of this workshop is to make signing into and using these methods easy and familiar.

Next, I'd like to see workshops on content creation, using applications such as Wavlake and Stemstr for music, using Highlighter and Habla.news for blogging, using Zap.stream and Nostr Nests for video and audio streaming, using Flare.pub for video uploading, using Flockstr and Seeker for your meetups, etc. We have a plethora of great Other Stuff applications that need more eyeballs and attention. I would like to see several workshops focus on this type of content for creators. Education both content creators and content consumers would be the end result of this workshop.

Every workshop should end with a 10+ minute Q&A sessions. Attendee interaction here is key. We want users to come away feeling like they learned something and can go home and use these various Nostr applications and apply their education.

### Is there anything attendees should read up on before they attend this talk?
Attendees could visit https://nostrapps.com to use applications and services that they wish to learn more about.
### Is there anything attendees should set up before the workshop?
For specific applications that they want to learn more about, they can bring their questions.
### Relevant Links

# About the Speaker
### Social Links
Nostr [derekross@nostrplebs.com](https://njump.me/derekross@nostrplebs.com)
Github [derekross](https://github.com/derekross)
Twitter [@derekmross](https://twitter.com/derekmross)
Website [derekross.me](https://derekross.me)

# Workshop Details
### Length of workshop
Any
### Preferred Day/Time Slot 
Any / Multiple :)

**Comment by sarahiscoding** [comment]
(ignore this, just writing my notes on here)

NERDS. ARTISTS. SOCIAL JUSTICE.

-----------------------------------------

**NERDS**
Common Theme: Past, Present, Future of Tech
Current State ---> Nostr Globalization ---> Tools to Succeed
Nerd Basics: Nostr 101, Apps & Tools, DVM, and AI (panel, AI is going to be a hot topic for a bit)

- Intro To Unconference, what to expect, how the layout of speakers (nerds, artists, SJ), and why it is important for each day ( update #31 )
- #19 : Nerd 101 for Non Techy
- #5 : Demo Nostr Ecosystem, What is Here?
- #1 
- #32 & #15 : Interoperability (quick highlight)
- #2 
- #37 : Before & After of Private Messaging and Groups
- #39 : Slack Alternative, might have Vitor talk about his idea of a separate notification app that works for all, possibly including this idea. The future planning. 
- #22 
- #29 
- #18 & #16 & #12 & #9: Advanced Nostr Workshops
- #27 : Part One of Two - How It Can Help Nostr? Negatives? Positives?
- #25 
-  Call to Action from new thinkers, coders, users, teachers, speakers, visitors

**ARTISTS**
Common Theme: Shopping
Current State ---> Nostr Globalization ---> Tools to Succeed
The Bull Marketplace: 21, 26, 30 (arranging it for what is currently happening in the centralized world to what nostr introduces to talks from creators,, such as OpenMike, Wavlake, Digital Nomads, of these apps to artists that are benefitting. 

- #21 : Love the idea of The Bull Marketplace, as a shopping mall/store concept to introduce Nostr, 4v4, Travel Agencies, Music, Books. 
- #26 : Feel like this can tie into this section 
- #30: Tower Records, Newbury Comics, Record Shops, Small Mom & Pop Shop kind of concept to introduce a new shopping experience, that is a win-win for customers and creators
- #24 : Crowdfunding: Part One of Two: Creators 
- #11 Talk Beyond (possibility of some topics entering SOCIAL JUSTICE)
- #17 
- #33 & #34 
- #4 : Part One of Two: As Creators 
- CTA

**SOCIAL JUSTICE** 
Common Theme: Communications
Current State ---> Nostr Globalization ---> Tools to Succeed
- #8 
- #3
- #35 Polling for SJ
- #37 & #10 : How can this help SJ Warriors? / Communications
- #14
- #4 : Part Two of Two: As Truth Tellers
- #27 : Part Two of Two: The Impact of AI on SJ
- #24 : Part Two of Two: Crowdfunding for Activism
- #36
- #6  
- #28 
- #38 

(In all speeches, workshops, reminder to speak highlights for 30 second or less highlight reels; transcript everything for articles, build all kinds of content from elements)
