### ISSUE TITLE
Marketplaces & "The Killer App"

### ISSUE THREAD

**Issue by calvadev** [nostrworld/nostriga#21]
# Description
### What is this talk about? Give us as many details as possible. 

Marketplaces and their potential to be the killer app for growth and interoperability.

Marketplaces are the most obvious next step for Nostr to attract more interest from people familiar with public-key cryptography, "crypto," or those just looking to use money online. The economic incentives baked into marketplace models can also lead to more sustainable product development. The potential for interoperability across several clients is also ripe for implementation, allowing the power of Nostr to truly shine. 

### What would an attendee learn from this talk?

- Current landscape of "fiat" marketplaces
- How Nostr can help break the misaligned incentives and silos within existing marketplaces
- Types of marketplaces that can be developed
- Possible business models and options for sustainable development
- Potential ways of improving interoperability across the network
- Applicable NIPs

### Is there anything folks should read up on before they attend this talk?

Not required, but great read to start thinking about interoperability over Nostr: https://highlighter.com/pablof7z/38iu6ttnk6zw3wdd

### Relevant Links

https://shopstr.store
https://plebeian.market/
https://github.com/vitorpamplona/amethyst
https://coracle.social/listings

# About the Speaker
### Social Links
Nostr - https://nostr.com/npub16dhgpql60vmd4mnydjut87vla23a38j689jssaqlqqlzrtqtd0kqex0nkq
Github - https://github.com/calvadev
Twitter - https://twitter.com/calvadev
Website - https://calva.dev/

# Talk Details
### Length of Talk

30 min.

### Preferred Day/Time Slot 

No preference.

**Comment by joshgaskin** [comment]
A big thing for marketplaces and for Nostr in general is that we need to bridge the gap for no-coiners. Tipping/paying for stuff shouldn't be just for bitcoiners. 

How can we create an experience where regular Joe can buy something on a nostr marketplace with bitcoin without even knowing it was bitcoin? What solutions do we have to pay with a card, convert the payment to btc and complete a transaction without even knowing it? 

I'm thinking theres an opportunity with cashu 

I need this for Tribly very soon.

**Comment by exfrog** [comment]
Seems like a good tie in with https://github.com/nostrworld/nostriga/issues/28 and https://github.com/nostrworld/nostriga/issues/26

**Comment by zsoerez** [comment]
excited to see shopstr in small markets
