### ISSUE TITLE
Finding Filemo: file indexing over nostr & distributed storage 🗄️🐡

### ISSUE THREAD

**Issue by alltheseas** [nostrworld/nostriga#22]
# Description
### What is this panel discussion about? Please give us as many details as possible. 

Nostr provides opportunity for folks to share the location of files with some combination of notes, hashes, signatures, zaps, CDNs, relays, and perhaps peers! 

### What would an attendee learn from this talk?

Learn about:
why and how guulagl drive will rugpull you, 
blossom drive,
bittorrent and nostr rabbit hole,
satellite CDN,
webRTC signaling over nostr for file transfers,
Direct nostr sync with friends, 
the pitfalls, and performance challenges of distributed file indexing and storage 

### Relevant Links

https://blossom.hzrd149.com/

https://github.com/nostr-protocol/nips/pull/1175

https://njump.me/nevent1qqsywt0ff77vflkjw3zr9htc36yepkx7ru5uum6h4pht8vpj3ljtydsvf5a3y

# About the panelist
### Social Links
Jb55
https://jb55.com/
https://github.com/jb55
https://njump.me/npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s
https://twitter.com/jb55

Hzrd149
https://hzrd149.com/
https://github.com/hzrd149
https://njump.me/npub1ye5ptcxfyyxl5vjvdjar2ua3f0hynkjzpx552mu5snj3qmx5pzjscpknpr

Martti Malmi
https://njump.me/npub1g53mukxnjkcmr94fhryzkqutdz2ukq4ks0gvy5af25rgmwsl4ngq43drvk
https://github.com/mmalmi
https://twitter.com/marttimalmi

Moderated by
elsat 

https://github.com/alltheseas
https://njump.me/npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5

# Panel Discussion Details
### Length of the panel discussion
30-45 minutes

### Preferred Day/Time Slot 
Dont overlap with panelists other events

**Comment by Sebastix** [comment]
Curious where https://www.hornetstorage.com/ currently stands.

And maybe also interesting: https://github.com/supertestnet/nostr-image-host

**Comment by melvincarvalho** [comment]
you may want to look at : https://nosdav.com/

**Comment by melvincarvalho** [comment]
Please also be aware that nump . me contains spyware

You might want to protect users privacy by using https://nostr.at/

**Comment by alltheseas** [comment]
> Please also be aware that nump . me contains spyware
> 
> 
> 
> You might want to protect users privacy by using https://nostr.at/
> 
> 
> 
> 

Whats the spyware on njump?

**Comment by exfrog** [comment]
Great topic! LGTM!

**Comment by gsovereignty** [comment]
Such an awesome topic idea @alltheseas!

**Comment by melvincarvalho** [comment]
> > Please also be aware that nump . me contains spyware
> > You might want to protect users privacy by using https://nostr.at/
> 
> Whats the spyware on njump?

It's still there I see.  

![image](https://github.com/user-attachments/assets/8cc10550-6f5f-4572-92c7-274d46c0fc62)

**Comment by ColbySerpa** [comment]
Love the nemo reference...

**Comment by Marce198** [comment]
Hey @alltheseas have you confirmed all your speakers for this panel are going to be present at the conference?

**Comment by alltheseas** [comment]
Double checking now - I expect speakers to be present based on my conversations :pray: 

@Marce198 when should I expect to hear back which panels, workshops, talks have been "approved" by the organizing crew? I'd rather not prepare things that will not be part of the conference.

**Comment by exfrog** [comment]
Hours, not days

**Comment by alltheseas** [comment]
@jb55 @mmalmi @hzrd149 see updated time

**Comment by alltheseas** [comment]
@v0l ser

**Comment by alltheseas** [comment]
@lovvtide ser

**Comment by alltheseas** [comment]
@jb55 is good to sit this one out, as @mmalmi suggested we add Nestr/Hornet Storagee teammate @ColbySerpa to the filesharing panel.

**Comment by ColbySerpa** [comment]
Looking forward to it.
