### ISSUE TITLE
Angor - A decentralized crowdfunding platform built on Bitcoin and Nostr 

### ISSUE THREAD

**Issue by dangershony** [nostrworld/nostriga#24]
# Description

Presenting Angor a decentralized crowdfunding platform

### What is this talk about? Give us as many details as possible. 

Angor is a platform with two unique features:

1. Angor is **fully decentralized**, meaning there is no middleman involved in the investment process. Angor has no backend – the platform leverages the **Bitcoin network** for transaction processing, while **Nostr** is being used for decentralized storage of projects' metadata and direct communication with founders. Angor uses Bitcoin's Taproot upgrade for improved efficiency and privacy.

2. Bitcoins are released to the founders in **predetermined stages** via timelock contracts, allowing investors to **recover unspent funds at any time**. This framework provides investors with greater control, mitigates financial risk, and incentivizes founders to showcase tangible progress between stages.

### What would an attendee learn from this talk?

Overview of how Angor works under the hood, the taproot scripts that are used and how we leverage Nostr.

### Relevant Links
* Specifications: bcip-0005 https://github.com/block-core/bcips/blob/main/bcip-0005.md
* Landing page https://angor.io/
* Source code https://github.com/block-core/angor

# About the Speaker
### Social Links
Nostr https://primal.net/p/npub1ldsmj0vxfe8sawnkdwu92medcqnzar5c2qfw9xazs5yd65sx0kvqghzsk3
Github https://github.com/dangershony
Twitter https://twitter.com/dangershony

# Talk Details
### Length of Talk
30 min
### Preferred Day/Time Slot 
no preference

**Comment by exfrog** [comment]
LGTM!

**Comment by rottenwheel** [comment]
This looks sick! Exciting.

**Comment by patrickReiis** [comment]
I have thought about something equivalent for years, thank god someone is doing it.

**Comment by itstomekk** [comment]
I want to see it

**Comment by dangershony** [comment]
Hi team, unfortunately my circumstances have changed and I won't be able to attend Nostriga this year.
I am sorry and disappointed as I was really looking forward to showing the Nostr community what we are working on, I very much hope to come to the next Nostr event ofcourse.

**Comment by dangershony** [comment]
> I want to see it

I will do my best to release a video presentation of Angor
