### ISSUE TITLE
Super(connected)intelligence on Nostr

### ISSUE THREAD

**Issue by dtdannen** [nostrworld/nostriga#27]
# Description
### What is this talk about? Give us as many details as possible.

This talk will present a vision for AI services on Nostr and ground that vision in the current state of the network and data vending machines as they are today. I will explain how Nostr and Bitcoin provide a better foundation than other previous attempts at realizing decentralized AI. I will highlight what data vending machines are and the benefits of a dynamic network of data vending machines. I will end the talk with guidance for developers working with data vending machines and guidance for all types of users to benefit from AI capabilities on Nostr, including what the future of work may look like.

I may also discuss:
- different levels of abstraction to think about decentralized AI and the level that Nostr solves
- building blocks of decentralized AI, what Nostr currently solves, what we need to solve in the future, and what Nostr+DVMs shouldn't try to solve
- why the social layer of Nostr is important to the whole picture. DVMs operating at the same level of abstraction as humans will enable human-in-the-loop AI systems. I will explain why decentralized AI working for/with/by/under humans will win, drawing from history in AI on robotics

### What would an attendee learn from this talk?

They will learn about decentralized AI, data vending machines, and perspectives to consider adopting for using and building AI applications on Nostr for the future.

### Is there anything folks should read up on before they attend this talk?

Optional, but will be helpful:
1. https://github.com/nostr-protocol/nips/blob/master/90.md
2. https://github.com/nostr-protocol/nips/blob/master/89.md
3. (fun read, lightly related) Rainbow’s End by Vernor Vinge
4. Short video demonstrating the benefit of human-robot interaction: https://www.youtube.com/watch?v=FGRLQRik6zs
5. [A Review on Building Blocks of Decentralized Artificial Intelligence](https://arxiv.org/pdf/2402.02885)
6. [Human-Agent Teaming as a Common Problem for Goal Reasoning](http://sce.carleton.ca/~mfloyd/publications/conference/2018/MolineauxFDA-AAAISS-SIRLE2018.pdf)

### Relevant Links

# About the Speaker

Dustin Dannenhauer has PhD in AI with expertise on agents and multi-agent systems, goal reasoning, metacognition, and planning and execution in unexpected, dynamic environments. 

### Social Links
Nostr: https://njump.me/nprofile1qyfhwumn8ghj7ur4wfcxcetsv9njuetn9uq3zamnwvaz7tmwdaehgu3wwa5kuef0qqsd5x8fscqypualfyu8dlqkkx539tj6dah634g4ns779wpr8gxes5g2rc7h6
Github: dtdannen
Twitter: (if you must, I rarely check it) https://x.com/drdannenhauer
Website: https://dtdannen.github.io/

# Talk Details
### Length of Talk

20-30 minutes, not including time for questions.

### Preferred Day/Time Slot
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

EDIT 1: Changed time from 20-30 minutes. I can modify the talk depending on the time available.
EDIT 2: Added a few points under "I may also discuss:"
EDIT 3: Added more supplementary material to the "What folks should read up on beforehand" section

**Comment by dtdannen** [comment]
I made a few edits to my talk and listed them at the bottom of the issue description

**Comment by dtdannen** [comment]
The title of my talk is currently quite bold - I'd like the option to change it if the organizers don't mind, especially as the content of my talk evolves.

**Comment by exfrog** [comment]
This seems like it would go great before your proposed dvm workshop.

**Comment by sarahiscoding** [comment]
I like the concept of AI talk in this new Nostr world. Could this be a panel with different viewpoints?

**Comment by dtdannen** [comment]
I like the idea of a panel on AI and Nostr. For this specific talk I need to use slides (I'll be showing diagrams and images). I'd like the opportunity to present some history and context for AI systems today and how Nostr DVMs fit into that picture. I can send a draft of the slides to organizers ahead of time if needed.
