### ISSUE TITLE
Separation of Business and State

### ISSUE THREAD

**Issue by gsovereignty** [nostrworld/nostriga#28]
# Description
When Bitcoiners want to collaborate on a commercial venture, they register a company.

The problem is that a company is a branch of the State. That's why "Bitcoin" companies like Strike, Unchained, and River have compliance departments. The State tells them what to do, and they do it. 

The State is **the adversary** in the Bitcoin security model. Bitcoin's *entire* value proposition is that it cannot be controlled by the State. If you use Bitcoin as a company you ban yourself from this separation of state and money because your Bitcoin activity is permissioned by the State (if you don't believe me, try sending coins from your company to someone on the OFAC list). 

What companies call "Bitcoin" is not genuine Bitcoin. Companies are using a State controlled "fork" of Bitcoin with modifications to include things like KYC and OFAC compliance. This fork is mostly interoperable with genuine Bitcoin for now, but that will rapidly change as we proceed deeper into phase two of the [war we are currently engaged in](https://www.youtube.com/watch?v=X_xgmVLyB94). 

Building a business in a way that is subject to State control is high time preference thinking because the State is ultimately going to rug every single one of them. By registering your venture and complying with **rules created by the adversary to Bitcoin**, you are banning yourself from the Bitcoin economy. Why would you spend time building something that is absolutely 100% guaranteed to be rugged like this? 

Until now we've lacked a robust and reliable way to coordinate the stakeholders in a commercial venture. We've had to use the State to mediate between stakeholders, enforce contracts, etc. Separation of Business and State has not been a viable option.

### What would an attendee learn from this talk?
People who watch my talk will learn why we urgently need to create separation of business and state, and how we can make it happen by using nostr as an alternative to company structures. 

# About the Speaker
[npub1mygerccwqpzyh9pvp6pv44rskv40zutkfs38t0hqhkvnwlhagp6s3psn5p](https://njump.me/npub1mygerccwqpzyh9pvp6pv44rskv40zutkfs38t0hqhkvnwlhagp6s3psn5p)

# Talk Details
### Length of Talk
30 minutes

# Time preference
First day, in the morning

**Comment by exfrog** [comment]
LGTM!

**Comment by Arvin21M** [comment]
> LGTM!

Lets Go! 🚀

**Comment by pablof7z** [comment]
ACKing but only of @gsovereignty promises to keep each slide to fewer than 400 words

**Comment by TheSvetski** [comment]
Looking forward to this one!

**Comment by dzdidi** [comment]
LFG :rocket:

**Comment by gsovereignty** [comment]
> ACKing but only if @gsovereignty promises to keep each slide to fewer than 400 words

😅

**Comment by rockstardev** [comment]
@gsovereignty we're accepting this talk for Nostriga, just would encourage you to give it a better name. Ask the public!

If I'm suggesting the name I would go with something direct like: `Nostr - Separation of Business and State`

**Comment by arcbtc** [comment]
Seperation of corps/neo liberalism and capital.
