### ISSUE TITLE
Tutorial on Data Vending Machines

### ISSUE THREAD

**Issue by dtdannen** [nostrworld/nostriga#29]
# Description
### What is this workshop about? Provide as many details as possible. 

This workshop will be a hands-on session where developers of all skill levels will learn about how data vending machines work at the basic level ([NIP-90](https://github.com/nostr-protocol/nips/blob/master/90.md)). We will cover libraries to help make DVMs, including the [nostrdvm](https://github.com/believethehype/nostrdvm) python library, and we'll talk about tools to debug DVM activity. Devs will have the opportunity to get their own DVM up and running during the workshop with help from the organizers.

### What would an attendee learn from this workshop?

Attendees will learn:
* DVM 101 for super newbies.
* How DVMs work under the hood, including the whole process from a user making a DVM request, to paying a DVM, to receiving content from a DVM
* Existing frameworks that make it easier to build and run your own DVMs, such as nostrdvm
* Tools for debugging DVM activity on Nostr

### Is there anything attendees should read up on before they attend this talk?

No, this workshop will be for those brand new to DVMs. Helpful reading would include:

- [Nip 90](https://github.com/nostr-protocol/nips/blob/master/90.md)
- [Nip 89](https://github.com/nostr-protocol/nips/blob/master/89.md)
- [nostr_sdk](https://github.com/rust-nostr/nostr/tree/master/bindings/nostr-ffi) bindings for the participants language of choice

### Is there anything attendees should set up before the workshop?

- [ ] Please set up a browser extension for Nostr login (alby or nos2x) so that you can submit DVM requests via https://vendata.io/ 
- [ ] Install python3.12 if you'd like to try using the nostrdvm library to create a DVM
### Relevant Links

# About the Speaker

Dustin Dannenhauer has a background in AI and is currently building [DVMDash](https://github.com/dtdannen/dvmdash) - a monitoring and debugging tool for DVM activity on Nostr. 

### Social Links
Nostr: https://njump.me/nprofile1qyfhwumn8ghj7ur4wfcxcetsv9njuetn9uq3zamnwvaz7tmwdaehgu3wwa5kuef0qqsd5x8fscqypualfyu8dlqkkx539tj6dah634g4ns779wpr8gxes5g2rc7h6
Github: dtdannen
Twitter: (if you must, I rarely check it) https://x.com/drdannenhauer
Website: https://dtdannen.github.io/

# Workshop Details
### Length of workshop

OLD: 90 - 120 minutes

NEW: 30 minutes should be enough time for the tutorial.

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

EDIT 1: added 'DVM 101 for Super Newbies' under what attendees will learn thanks to sarahiscoding

**Comment by dtdannen** [comment]
I am open to co-organizing this with other folks, so if anyone is interested please reach out to me.

**Comment by exfrog** [comment]
Great topic!
LGTM!

**Comment by sarahiscoding** [comment]
Addition:

What would an attendee learn from this workshop?

DVM 101 for super newbies.

**Comment by dtdannen** [comment]
@sarahiscoding I edited the issue to include your comment

**Comment by dtdannen** [comment]
After thinking about this more, we can do this tutorial in 30 minutes.

**Comment by dtdannen** [comment]
Here are the slides for the participants to follow along

https://dvmdashbucket.nyc3.cdn.digitaloceanspaces.com/Final_Data_Vending_Machines_Tutorial.pdf
