### ISSUE TITLE
Nostr is not censorship-resistant: Blastr, Outbox and shadowbanning on nostr

### ISSUE THREAD

**Issue by pablof7z** [nostrworld/nostriga#3]
# Description
Is nostr decentralized? Does it matter?
There's a lot of confusion about how finding data on nostr works, should we all connect to a central relay and be done with it? Does blastr fix this? What the hell is the outbox model?

# Key Points
* The Debate: Exploring the contrasting perspectives on the Outbox model versus the Blaster approach.
* Centralization Concerns: The role of relays in data aggregation and distribution. We'll discuss how reliance on a few relays for data access can lead to censorship vulnerabilities, increase the cost of operating relays, highlighting how the Outbox model (or something like it) is a requirement for a social-media/town-square use of nostr.
* Inefficiency and difficulty concerns about implementing outbox: There's been a lot said about the issues and the difficulty in implementing the outbox model as well as it's privacy and security concerns. We'll cover some of the numbers that have been floated around, the various approaches outbox implementations have taken and the tradeoffs in data inefficiency.

Chat between Tony and Pablo

# About the Speaker
https://njump.me/tonygiorgio.com
https://njump.me/f7z.io

# Fireside Details
30min

This fireside is not just a technical discussion but a critical examination of Nostr's path towards a more resilient and user-friendly platform. By comparing these two approaches, we aim to shed light on the complexities of building a decentralized social network and the ongoing efforts to make Nostr a robust platform for free expression and information sharing.

**Comment by alltheseas** [comment]
Can you also discuss if purplepages relay/profile indexer fixes censorship
