### ISSUE TITLE
Fix the outbox, fix the Nostr dev workshop

### ISSUE THREAD

**Issue by alltheseas** [nostrworld/nostriga#32]
# Description
### What is this workshop about? 

Outbox is lauded as the solution to fixing nostr. 

However, there is uncertainty surrounding the spec, or lack thereof, and best practices, or lack thereof.

Missing notes, missing profiles are crap user experience, and reduce nostr interoperability. If nostr is not interoperable nostr will never have a shot being a better experience than corporate privacy hell ad empires twitter et al, much less have a chance of being 10x, or @pablof7z (100x+) better.

Provide as many details as possible. 
### What would an attendee learn from this workshop?

This is a dev workshop. 

Ideal outcomes: 
1) what is the gossip spec today
2) what is the gossip best practice today
3) what is uncertain about 1), and 2) 
4) what are the blind spots of gossip implemented in best practice mode
5) how do nostr apps handle gossip model failure
6) what are the best practice characteristics of gossip implementation? 
7) can there be multiple implementations that satisfy shared best practices? 

### Is there anything attendees should set up before the workshop?

Read up on gossip best practice state

Https://njump.me/nevent1qqsy2cd6j4c6zcgcs95amcl4psrvfnrpthsuven5l3wnvfgunzxkf2spzpmhxue69uhkummnw3ezumrpdejqzxrhwvaz7tmddahxzepwdf3r2dfwvdhk6w3cxqurqqgkwaehxw309aex2mrp0yh8qunfd4skctnwv46qz9thwden5te0wfjkccte9ekk7um5wgh8qatzyhkgjf

### Relevant Links

# About the Speaker
### Social Links
Elsat - workshop host
Github - alltheseas

Outbox expert @pablof7z 
Alpha dev 2
Alpha dev 3

# Workshop Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by alltheseas** [comment]
@pablof7x advises

> To be clear: outbox is not a spec; it can’t be a spec for the same reason you can’t soec how running should work, some people want to sprint, some people have longer legs, some people have flat feet.

> Beyond defining running as “moving forward” and outbox as “getting events from relays where events might be” you’d start to define things too-narrowly.

**Comment by Sebastix** [comment]
I will attend for 100%

**Comment by exfrog** [comment]
Is the gossip / nostr outbox model mature enough at this point to have a workshop on it, or would another format, like a panel discussion, be more effective? (serious question as a non-dev).

**Comment by alltheseas** [comment]
There's a few implementations out in production. 

Ideally I get a mix of devs who have implemented, and a few with outbox on their to-do list, so that we can have practical outcome from this session with lively Q&A that we can also transpose for devs who cannot make it to nostriga.

**Comment by pablof7z** [comment]
> Is the gossip / nostr outbox model mature enough at this point to have a workshop on it, or would another format, like a panel discussion, be more effective? (serious question as a non-dev).

we already did a panel on ti in nostrasia and it was largely a waste of time

**Comment by alltheseas** [comment]
@pablof7z would you be open to leading/participating as a dev with real world gossip practice to answer questions from devs who have outbox on their roadmap - for instance @tyiu @jb55

**Comment by pablof7z** [comment]
> @pablof7z would you be open to leading/participating as a dev with real world gossip practice to answer questions from devs who have outbox on their roadmap - for instance @tyiu @jb55

yeah, sure, I have a ton to say about outbox 😂

**Comment by pablof7z** [comment]
but pleeeeease can we not name the talk "gossip" -- it's too confusing -- it's "outbox" 🙏
