### ISSUE TITLE
Nostr: "Social As A Service"

### ISSUE THREAD

**Issue by TheSvetski** [nostrworld/nostriga#33]
# Description

Nostr: "Social As A Service"

### What is this talk about? Give us as many details as possible. 

The talk would be based on an essay I wrote a few weeks ago, which takes a non-technical and more "product" look at Nostr. Nostr is many things, but this framing has been VERY powerful for when I've pitched Normies on the idea of Nostr, and why they should consider it.

https://substack.com/home/post/p-144993488

Ultimately, we as the Nostr community need to think OUTSIDE of the box, and we need to start changing the public perception that Nostr is just another "twitter clone."

I want to draw from our experience in building Satlantis so far, to get people to think about what it really means to build something new. 

### What would an attendee learn from this talk?

The idea is to get people thinking OUTSIDE of the box, and imagine how different kinds of online products & services could embed a social layer. 

We don't want to just continue building Web2.0 clones.
We need to think about how to integrate Nostr's open social graph into many other applications.

Also - Most people will argue that "you HAVE to be able to quickly put a product in a category" so that people know what it's for, like "Uber for X" - but I believe that if we want to build something new, we have to take a different path.

So I will drive home this point, from a product & business perspective (less on tech).

### Is there anything folks should read up on before they attend this talk?

The essay here: https://substack.com/home/post/p-144993488

### Relevant Links

# About the Speaker
Svetski: Author & Entrepreneur. 

Wrote “UnCommunist Manifesto” and "Bushido of Bitcoin”.  Built the world’s first Bitcoin-only savings app: Amber. Recently open sourced the first Bitcoin LLM (The Spirit of Satoshi) and is now working on the Nostr-based Travel & Community Social Network: Satlantis.

### Social Links
Nostr: https://Primal.net/svetski
Github:  https://github.com/TheSvetski
Twitter: https://Twitter.com/SvetskIWrites
Website: https://Linktree.com/Svetski

# Talk Details
### Length of Talk: 
15-20min
### Preferred Day/Time Slot: No preference. 
Whenever you think it's most useful.
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by exfrog** [comment]
@TheSvetski How does this keynote compare against the similar fireside chat you've proposed?  The topics seem similar. If you had to choose just one, which would you rather do?

**Comment by TheSvetski** [comment]
@exfrog - they are similar to some degree, although with the fireside was going to focus more on Satlantis as an implementation of something that is using Nostr, but not necessarily a social network in the same way as other products today are (eg; Damus / Primal, etc). And that format probably suits better to a fireside, because the interviewer + audience will certainly have questions about the product.

Whereas the keynote would be more abstract and build on the fireside. Here I would discuss the broader idea of using Nostr as a social graph to embed into many different online products & services.

The biggest two similarities would be that I'd approach both as a product person, and less as a technical person or developer. So hopefully that will bring another useful perspective to Nostriga.

That all being said, if you think they're too similar, happy to do just one, our evolve one of the topics.
Let m know what you think is best.

**Comment by Sebastix** [comment]
> We need to think about how to integrate Nostr's open social graph into many other applications

This is what I 'preach' as well. 
There are many types of applications you can mention. And I think Nostr coulb be embedded in existing services and platforms as well for several reasons (features). I'm calling it the legacy web 🙃

**Comment by TheSvetski** [comment]
> @TheSvetski How does this keynote compare against the similar fireside chat you've proposed? The topics seem similar. If you had to choose just one, which would you rather do?

After further discussions, I've fixed this and the other one.
Please have a look and let me know.
AS

**Comment by gsovereignty** [comment]
Looking forward to hearing @TheSvetski shake things up a bit with this one.

**Comment by TheSvetski** [comment]
@exfrog - confirmed for this, or the other, or both ?
Or neither?
