### ISSUE TITLE
Nomading & Network State on Nostr

### ISSUE THREAD

**Issue by TheSvetski** [nostrworld/nostriga#34]
# Description
### What is this fireside chat about? Give us as many details as possible. 

The only thing growing faster than Bitcoin today (that matters) is the Network State or Nomad movements. In 2019, there were 5m digital nomads worldwide. There are now almost 40m. Yes - FORTY MILLION.

I've been a part of this community for many years, having been to 50 countries and lived in 6 (on 4 different continents).
There is a BIG opportunity for us to tap into this market, if we build a product for them - and that's specifically what we've set out to do with Satlantis.io - the first "Travel, Community & Nomad Social Network".

Not only do we need sovereign money, but we need to establish as many parallel networks as possible.
Nostr enables SO MUCH of this, and I believe we can dig into these elements via a great fireside chat.

### Who is the person being interviewed?

Svetski (me)

### Who is the person that should conduct this interview?

Pablo, since he is also a traveller and is doing home-schooling around the world.
If he's busy, then Tanja who's doing the "Nostr Booth" initiative.

### Is there anything folks should read up on before they attend fireside?

I wrote a little about this in the following note:
https://primal.net/e/note152u25njjtg45vm9xpzxpedgceadznwacp7lzh0jdv9ualxja6jvsxu9lq6

### Relevant Links

https://primal.net/e/note152u25njjtg45vm9xpzxpedgceadznwacp7lzh0jdv9ualxja6jvsxu9lq6

# About the Speaker
### Social Links
Nostr: https://primal.net/svetski
Github: https://github.com/TheSvetski
Twitter: https://twitter.com/svetskiwrites
Website: https://linktree.com/svetski

# About the Interviewer
### Social Links
Nostr: https://primal.net/p/npub1hqaz3dlyuhfqhktqchawke39l92jj9nt30dsgh2zvd9z7dv3j3gqpkt56s
Github 
Twitter: https://twitter.com/svetskiwrites
Website

# Fireside Details
### Length of Fireside
20-30min

### Preferred Day/Time Slot 
Whenever Pablo and/or Derek are available.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by exfrog** [comment]
@TheSvetski have you reached out to Avi about this?

**Comment by TheSvetski** [comment]
@exfrog - ok just spoke with Avi - looks like he won't be able to make it.
I asked Derek. Waiting on response.
If you have any other suggested persons, let me know.
Otherwise Pablo & I could do something together, since he's one of the first people I told about Satlantis & has been following along since the beginning.

**Comment by TheSvetski** [comment]
ok - @exfrog - Derek said he'd like to do it.
I've thought a little more about this, and I think a better angle here would definitely be to lean into:

- Using Nostr to build parallel systems in the real world (A Network State Angle)
- Building for Digital Nomads
- Using Nostr to reinvent the map (I can discuss how we're using Open Street Maps as the base identifier and enriching Nostr with it & vice-versa)
- We can then dig into how a product like Satlantis is only possible on Nostr 

Let me know thoughts and if you like that angle, I can edit the original submission.

**Comment by sarahiscoding** [comment]
Digital Nomads is an interesting title

**Comment by TheSvetski** [comment]
@exfrog - I updated the title & the theme.
I think it is MUCH stronger now. Thankyou for the initial nudge.

**Comment by exfrog** [comment]
have you confirmed whom might join you on this?

**Comment by TheSvetski** [comment]
Pablo said he'd do it.

**Comment by exfrog** [comment]
@TheSvetski
Wtf man? After all this you no call no show?
Absurd!

**Comment by TheSvetski** [comment]
@exfrog 
Not absurd at all. 
Unfortunately the Brazilian authorities are retarded and didn't issue my ID card in time, and if I left overseas, I would have the start the entire 6mth process AGAIN. So not worth the headache. 
I had no means of contacting you (felt that messaging here would be strange), so I told Pablo, Tanja, Derek and some other people that I know there to find a way to let you know.
I also asked Tanja & Pablo to take the slot on my behalf.
Hope that clarifies.
