### ISSUE TITLE
Speaking Truth to Power

### ISSUE THREAD

**Issue by rockstardev** [nostrworld/nostriga#36]
## Description
It would be great to have a panel discussion on profound implications of Julian Assange's capture on global press freedom and the pivotal role of the cypherpunk movement in pushing the boundaries of privacy and transparency. This panel would explore how cryptography has become a vital tool in protecting whistleblowers and ensuring the free flow of information in the digital age. Through personal reflections, strategic discussions, and a look into the future, the panelists would share their insights and experiences on mobilizing global support for press freedom, empowering activists, and safeguarding freedom of speech.

## Key Topics
- The impact of Julian Assange’s capture on press freedom around the world
- Cypherpunks and the Fight for Privacy and Transparency, how cryptography has helped protect whistleblowers
- How FOSS and Nostr contribute to the freedom of speech
- Personal reflections and challenges - Stella sharing how their journey was, what were the challenges and hopes for the future
- Mobilizing global support and advocacy - strategies for mobilizing support for Julian Assange and the broader movement for press freedom and digital privacy
- Looking to the future - how do we empower more freedom of speech activists and speaking truth to power?

## Panelists
- Stella Assange
- Giacomo Zucco

## Moderator
- Rockstar Dev

# Extra Details
Will need to be scheduled on Aug 23, to accommodate for Stella's travel

**Comment by sexylibrarian** [comment]
While I find the theme of speaking truth to power attractive, may I suggest a separate panel talk on Nostr, Journalism, freedom tech business models etc. Obtaining information via hacking and journalism practices are two different topics. I nominate Efrat Fenigson lead the panel, as I'm just launching Independent Voice (and have been consumed by MyLibrarian). I've reached out to her and we'll submit a proposal soon.
