### ISSUE TITLE
The past & future of DMs and Private Group chats on Nostr

### ISSUE THREAD

**Issue by erskingardner** [nostrworld/nostriga#37]
# Description

This will be a discussion summarizing the past NIPs that covered DMs and Private Groups and then discuss the NIPs that are on the horizon. We'll talk about how clients/apps are using these NIPs in the wild and what trade-offs each of the approaches has.

The people on the panel will be me, @abhay-raizada (Formstr dev and helping on @islandbitcoin's Flash app), and anyone else I can get to join that has had a hand in the various DM and group messaging specs. (@vitorpamplona, @staab, etc)

# Fireside Details
### Length of Fireside

30-45min

### Preferred Day/Time Slot 

Sometime (preferably just) before the Double Ratchet DM talk I'm planning on giving.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by vitorpamplona** [comment]
Nice! Happy to join.

**Comment by staab** [comment]
I'd be happy to join, but only via telepresence robot since I won't be at nostriga.

**Comment by erskingardner** [comment]
> I'd be happy to join, but only via telepresence robot since I won't be at nostriga.

WAAAAT!?!? How can this be??

**Comment by staab** [comment]
The robot or my absence?

**Comment by rockstardev** [comment]
just to let you know that remote joins will be very unlikely (we may make 1-2 exceptions like at Nostrasia for Snowden and @fiatjaf)

also, love to see you'll be joining us in Riga @vitorpamplona!

**Comment by erskingardner** [comment]
> The robot or my absence?

Your absence, of course.

**Comment by staab** [comment]
> just to let you know that remote joins will be very unlikely

Oh yeah, I figured, there's no substitute for really being there. Sad to miss it!

**Comment by exfrog** [comment]
LGTM

**Comment by vitorpamplona** [comment]
Hey folks, sorry I had a change of plans and won't be able to make it to nostriga :(

**Comment by alexgleason** [comment]
Someday I would like to meet @vitorpamplona in real life.

**Comment by vitorpamplona** [comment]
Real life is overrated 😅

**Comment by abh3po** [comment]
Wouldn't be able to join in, but I do suggest @islandbitcoin joins this himself.

**Comment by exfrog** [comment]
@erskingardner looks like this is a fireside conversation between you and yourself at the moment....  you still wanna do this and find some people to throw on stage, or are we removing it?

**Comment by erskingardner** [comment]
I really want to do it but happy to make a talk of it. It’s a shame because all the other nip-17 DM folks aren’t going to be there. On 17 Aug 2024, at 02:08, exfrog ***@***.***> wrote:﻿
@erskingardner looks like this is a fireside conversation between you and yourself at the moment....  you still wanna do this and find some people to throw on stage, or are we removing it?

**Comment by vitorpamplona** [comment]
A talk explaining the MLS proposal could be interesting

**Comment by erskingardner** [comment]
@exfrog What about the idea of making this a short talk plus slightly longer Q&A. I think there are likely going to be lots of questions about tradeoffs etc in the new DM spec or why it's even needed in the first place. Might be better as an interactive format?

**Comment by exfrog** [comment]
Sounds good to me!
