### ISSUE TITLE
Nostr as comms and other stuff for companies

### ISSUE THREAD

**Issue by Arvin21M** [nostrworld/nostriga#39]
- All corporations deal with 3rd party vendor stacks from hell, at varying degrees. 
- Some of the easier ones to remove from their stacks would be ones that nostr can provide solutions for, by bringing them back in-house.  
- Solving problems for enterprises using nostr could be lucrative for the devs and organizations creating these solutions.
- Would be great to see content or a discussion around this topic.
---
- Replace 3rd party chats with self-hosted chat
- Integration w/existing intranet
- In-house relays to support internal comms
- Spin up custom clients for diff org teams/needs
- Use for secure file sharing 
- Reduce 3rd party reliance for enhanced security & fewer compliance headaches
- And other stuff

**Comment by alltheseas** [comment]
Death to slack

**Comment by exfrog** [comment]
@Arvin21M Is this a topic you have a presentation for or just a topic you want to see covered?

**Comment by Arvin21M** [comment]
@exfrog This is something I would love to see covered. 

I have domain expertise in selling software solutions to enterprises.

However, I do not have specific nostr domain expertise to speak on the details of programming and servicing these solutions for enterprises.

**Comment by exfrog** [comment]
@Arvin21M Take a look at https://github.com/nostrworld/nostriga/issues/28

It seems somewhat like what you are proposing here?

**Comment by Arvin21M** [comment]
@exfrog [#28](https://github.com/nostrworld/nostriga/issues/28) seems like it would be something that comes into play when some of the required nostr solutions are identified for these enterprises, and now it's time to properly organize relationships/partnerships/efforts to make it happen. 

This one [(#39)](https://github.com/nostrworld/nostriga/issues/39) is more of an exploration of the possibilities with some of the nostr projects that are in alpha/beta/launched right now, and some that are slated for release soon.

**Comment by exfrog** [comment]
> @exfrog [#28](https://github.com/nostrworld/nostriga/issues/28) seems like it would be something that comes into play when some of the required nostr solutions are identified for these enterprises, and now it's time to properly organize relationships/partnerships/efforts to make it happen. 
> 
> This one [(#39)](https://github.com/nostrworld/nostriga/issues/39) is more of an exploration of the possibilities with some of the nostr projects that are in alpha/beta/launched right now, and some that are slated for release soon. 

I think it's a great topic, but needs a leader/coordinator to find the right people to put on stage imho

**Comment by Arvin21M** [comment]
@exfrog Yes! I think some of the people already slated to speak at Nostriga would be knowledgeable about this topic. @gsovereignty and @pablof7z come to mind, of course.
