### ISSUE TITLE
Jack US president

### ISSUE THREAD

**Issue by joanna2028** [nostrworld/nostriga#40]
# Description
### Is there anything folks should read up on before they attend fireside? Nostr

# About the Speaker 
[primal.net/npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m](http://primal.net/npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m)

# About the Interviewer 
[primal.net/p/npub1pkx92m60skq9pzs90m3yqq9tvwh03xhzc0haeqqc4exjcu7l6ntsanxwks](http://primal.net/p/npub1pkx92m60skq9pzs90m3yqq9tvwh03xhzc0haeqqc4exjcu7l6ntsanxwks)

let's see if I'm a great campaign chairman
J (?)

**Comment by rockstardev** [comment]
6 NACKs, rejecting the proposal and closing the issue.
