### ISSUE TITLE
Talk: Code Collaboration Via Nostr

### ISSUE THREAD

**Issue by DanConwayDev** [nostrworld/nostriga#44]
# Description
### What is this talk about?

We the cypherpunks create anti fragile tools to defend our liberty using collaborative platforms controlled by the very powers who seek to threaten it.
 
This talk will explore:
* why this is problematic
* how nostr can provide an alternative with NIP34
* what progress has been made
* how you can get involved

find out how:
* nostr can seamlessly integrate with git and git tools; and how
* the collaborative experience integrates with existing social nostr clients alongside dedicated clients such as gitworkshop.dev

### Relevant Links

https://gitworkshop.dev

# About the Speaker

DanConwayDev - creator of ngit and gitworkshop.dev
nostr:npub15qydau2hjma6ngxkl2cyar74wzyjshvl65za5k5rl69264ar2exs5cyejr

# Talk Details
### Length of Talk
20 mins
### Preferred Day/Time Slot 
flexible

**Comment by alltheseas** [comment]
Is this a workshop?

**Comment by DanConwayDev** [comment]
I envisioned this as more of a talk with a demo.
I could potentially do a workshop, leading attendees through the process of creating a repository, submitting proposals, commenting on them, etc.

**Comment by alltheseas** [comment]
> I could potentially do a workshop, leading attendees through the process of creating a repository, submitting proposals, commenting on them, etc.

This would be interesting for me.

**Comment by DanConwayDev** [comment]
> This would be interesting for me.

I have submitted a companion workshop https://github.com/nostrworld/nostriga/issues/48
