### ISSUE TITLE
Openness Is Nostr's Killer Feature

### ISSUE THREAD

**Issue by mbrat1** [nostrworld/nostriga#45]
# Description
Nostr is at the cusp of breaking out of the “Twitter clone” narrative. We now have the building blocks for a diverse set of applications. When built correctly, each Nostr app contributes its own building blocks, which are open to the rest of the network. The resulting ecosystem of apps will be vastly superior to that of the legacy Web. 

In this talk, we will cover: 

- Core Nostr building blocks 
- Building Nostr apps correctly 
- Talk is cheap; let’s see real examples
- Developer network effects 
- Why Nostr wins 

# About the Speakers
Miljan 
npub16c0nh3dnadzqpm76uctf5hqhe2lny344zsmpm6feee9p5rdxaa9q586nvr 

Pablo
npub1l2vyh47mk2p0qlsku7hg0vn29faehy9hy34ygaclpn66ukqp3afqutajft 

# Talk Details
### Length of Talk
30 minutes 

### Preferred Day/Time Slot 
Early on Day 1

**Comment by thebullishbitcoiner** [comment]
Bullish on the developer network effects. I've learned so much from studying and running other devs' code. 👍

**Comment by somkirannmuster** [comment]
Nostr will evolve as the glue for many new use cases, applications bringing the Zaps, resistance free socials, profiles etc. It could also evolve as the default Web2-Web3 bridge bringing many new users without worrying about the backend stack - organic onboarding

**Comment by derekross** [comment]
If the phrase "social glue" will be used at least once, this topic and my full support 😁

**Comment by ttiiggss** [comment]
Looking forward to building Nostr apps correctly! Would love to know more about the best process(es) you guys have found for teaching or understanding Nostr in a linear method (if applicable).

**Comment by modl21** [comment]
ACK
