### ISSUE TITLE
Design for Communities

### ISSUE THREAD

**Issue by NielLiesmons** [nostrworld/nostriga#46]
# Description
This panel is about how to design Nostr tools for Communities (around certain interests or creators).
### What will be discussed:
- Specific UX/UI patterns that optimize for Communities and NOT for public squares
- What Community Admins and Creators say they want VS What they actually need (in a radically free market)
- Monetizing Communities VS Monetizing Content 
- The exciting new design space of Interoperable Communities

# About the panelists
**Linda** 
Head of Product at Nos.social
_npub1j60x528w2g2vkq5kae5uhh8y7sezjyj20zcsg0v9muc72cmdpu0s0md7ua_
She will share insights from the Creator Residency and Journalism Accelerator programs including feedback from participants on their experience building an audience on Nostr,  as well as results from topical relay experiments we’re running to support creators and journalists

**Niel Liesmons**
Nostr Designer at Opensats
_npub149p5act9a5qm9p47elp8w8h3wpwn2d7s2xecw2ygnrxqp4wgsklq9g722q_
He will share insights from his design work on several Creator- and Community-focused Nostr apps. 

**Saunter*
UX Designer at Alby
_npub1m0sxqk5uwvtjhtt4yw3j0v3k6402fd35aq8832gp8kmer78atvkq9vgcru_
He will share insights on monetization from his design work at Alby and several related projects (Alby Hub, Nostr Wallet Connect, Bitcoin Layers, ...)

# Panel Discussion Details
### Length of the panel discussion
30-40 min
### Preferred Day/Time Slot 
No preference

**Comment by itstomekk** [comment]
Hmm how about bringing @stackingsaunter?
He has nice growing portfolio and experience!

**Comment by NielLiesmons** [comment]
Yes! Saunter would be great indeed.
Asked him on Nostr too.

**Comment by NielLiesmons** [comment]
> Hmm how about bringing @stackingsaunter? He has nice growing portfolio and experience!

If ever you think of a Content Creator that you know will be there  👉  I'm all ears.

**Comment by stackingsaunter** [comment]
I'm up for this!

**Comment by NielLiesmons** [comment]
Awesome! Added you to the description.
