### ISSUE TITLE
POSSE - how we pivot away from API's with one of Nostr superpowers

### ISSUE THREAD

**Issue by Sebastix** [nostrworld/nostriga#49]
# Title
**POSSE - how we pivot away from API's with one of Nostr superpowers**
## Description
Nostr integration could enable POSSE for many widely used applications, services and platforms. I expect that some big (web legacy) platforms will unsilo themselves with Nostr.
### What is this talk about? Give us as many details as possible. 
With Nostr the data interoperability property is moving from the application (API) layer to the protocol layer.
It’s not only the content that’s portable, also related comments and other kind of reactions are.
With Nostr your social graph is interoperable as well and this is pretty unique compared with other open protocols focused on building communication applications and platforms.
In this talk I will show the recent innovations around POSSE (and Nostr), like
* stacker.news 
* mixpost.app
* OpenVibe
* Noottii
* Ghost (ActivityPub)
* Drupal
### What would an attendee learn from this talk?
It will give you a fresh new insight how the Nostr protocol gives portability to your content by default. 
### Is there anything folks should read up on before they attend this talk?
https://indieweb.org/POSSE 
### Relevant Links

# About the Speaker
Sebastian Hagens
### Social Links
Nostr - https://nostr.com/npub1qe3e5wrvnsgpggtkytxteaqfprz0rgxr8c3l34kk3a9t7e2l3acslezefe 
Github - https://github.com/sebastix 
Website - https://sebastix.nl & https://nostrver.se 
# Talk Details
### Length of Talk
20-25 minutes
### Preferred Day/Time Slot 
I will attend Nostriga fulltime both days, so any slot will be fine.

**Comment by jurjendevries** [comment]
Interesting point of view for Nostr
