### ISSUE TITLE
Nostr is Freedom for Creators—Better Business Models for Sustainability

### ISSUE THREAD

**Issue by sexylibrarian** [nostrworld/nostriga#51]
Panel Proposal 1: Nostr is Freedom for Creators—Better Business Models for Sustainability

What do all content creators have in common? The desire to connect with their audience and spark conversation in their community and the need to be compensated for it. 

Our Nostr and Journalism talk for the Nostriga Unconference will be a roundup of Nostr apps for content creators, and their developers, if on-site to participate. We’ll curate a lively and informative discussion on how creators can get paid, so we can implement Zaps via the Lightning Network and keep creating.

We’ll cover Nostr adoption and Zap implementation for all content creators, including Journalists, Bloggers, Publishers, and Writers. Michelle Z will speak to MyLibrarian’s creator community on Nostr, where besides Zapping creators, MyLibrarian uses Zaps as a payroll tool, to send profit-sharing micropayments.

Curated by Michelle Z
npub1jdyaqyngdj4tgmmtlm7j7npkr3fwzjcumcwdqf68dc9wd5lf39rqwlfwsu
More About Michelle Z
An advocate of freedom tech and expression of truth, Michelle spent 10 years working as a journalist in New York for Hearst Corp. Upon moving to San Francisco, she learned to code and founded the book review journalism startup MyLibrarian / In the Stacks ([LibrarianBrain.com](url)). She’s also the author of 6 novels, including her freedom tech novel ALLEGRA, about Pasquino, the first talking statue of Rome, who was the Renaissance equivalent of posting or blogging the truth. Read more about the book here [](https://www.michellezaffino.com/3069/)

# Description
### Relevant Links

# About the panelist
### Social Links
Nostr
GitHub 
Twitter
Website

# Panel Discussion Details
### Preferred Day/Time Slot **ANY**
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by HeatherLarson** [comment]
Getting creators paid is the name of the game here, folks. There's only more censorship of journalists worldwide. The social platforms are getting worse with it, too. Meta has made it clear "news" and "politics" won't be promoted there. I can't even share a link to a playlist on Fountain without Facebook deleting it immediately. It's tougher than ever to be a creator online, whether that's a writer, musician, journalist, photographer, etc.

**Comment by SusieViolet** [comment]
Zaps make my day, and supporting content creators through zapping is even more rewarding. However, it's frustrating that I earn the same modest amount whether writing a generic NGU article or deeply investigating topics like Ripple's anti-Bitcoin campaigns or biased sh*tcoin research. Quality journalism often means financial sacrifice, and the challenge is exacerbated by short attention spans driven by social media. How can we reverse the damage caused by mainstream media while making investigative journalism economically viable?

**Comment by sexylibrarian** [comment]
Hi, here’s an update on this presentation. I’ll be presenting solo with slides. The talk will be mentioning all the cool tools for creators on Nostr.Can you please update the headline to read, “Nostr is Freedom for Creators—Better Business Models for Sustainability.” If you want an outline of the talk I’ll have one soon. I’ll be talking about the products of all the devs I mentioned as possible speakers, and more. Cheers—MichZSent from my iPadOn Aug 14, 2024, at 12:54 PM, Susie V ***@***.***> wrote:﻿
Zaps make my day, especially when supporting content creators. However, it's frustrating that I earn the same modest amount whether writing a generic NGU article or deeply investigating topics like Ripple's anti-Bitcoin campaigns or biased sh*tcoin research. Quality journalism often means financial sacrifice, and the challenge is exacerbated by short attention spans driven by social media. How can we reverse the damage caused by mainstream media while making investigative journalism economically viable?
