### ISSUE TITLE
Nostr Is Freedom Journalism—Independent Voices

### ISSUE THREAD

**Issue by sexylibrarian** [nostrworld/nostriga#52]
Panel Proposal 2

Independent Voices

One of the most valuable features of Nostr is that no one can be censored, and everyone has a voice. With a large enough audience, and with currency of time spent, amplification and micropayments zapped, there is a viable business model. 

This new business model gives hope to freedom journalism and allows writers and editors of all types to earn a living from their work. Journalism is the fourth estate, holding government and religious institutions accountable. Transparency, accuracy in reporting and fact-checking is more important than ever, in this age that has become increasingly full of misinformation. 

Nostr gives real hope to society, as an outlet for freedom of expression and respect for each of us to examine information critically and make up our own minds.

 At Nostriga, we’ll assemble a panel of independent journalists, from diverse publications, to share how we are using Nostr to build our businesses and audience. 

Nostr is a real solution for journalists to be self-sufficient and truly have an Independent Voice.

Curated by Michelle Z
npub1jdyaqyngdj4tgmmtlm7j7npkr3fwzjcumcwdqf68dc9wd5lf39rqwlfwsu
More About Michelle Z
An advocate of freedom tech and expression of truth, Michelle spent 10 years working as a journalist in New York for Hearst Corp. Upon moving to San Francisco, she learned to code and founded the book review journalism startup MyLibrarian / In the Stacks ([LibrarianBrain.com](url)). Michelle hosts monthly author interviews for MyLibrarian and popular culture discussions via the talk show Independent Voice.

Update: Susie Violet will be joining Michelle Z on the panel. Susie is a Journalist and Co-founder and Head of Mining & Energy at Bitcoin Policy UK
npub1hwgw0uznr49t4gullpgfz4m5xnakl5a0l88m3k382xv7ys0tfmlsd503sg

Also joining is Linda from Nos
npub1j60x528w2g2vkq5kae5uhh8y7sezjyj20zcsg0v9muc72cmdpu0s0md7ua

Discussion Topics
Old Journalism, New Journalism, Old Money, New Money
Content vs. Verified and Fact-Checked Balanced Reporting
Robin Hood-style information hacking vs. Verified and Fact-Checked Balanced Reporting
How traditional standards of journalism can endure vs. the unethical advertising models of recent years, including pay for publication.
Activist journalism vs. Verified and Fact-Checked Balanced Reporting
Rich media owners of media companies and social networks whose intentions are to influence politics and business through their publications.

And how Nostr frees us from being beholden to any bias and manipulation. 
# Description
### Relevant Links

# About the panelist
### Social Links
Nostr
GitHub 
Twitter
Website

# Panel Discussion Details
### Preferred Day/Time Slot **ANY**
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by efenigson** [comment]
Censorship these days is one of the toughest "pandemics" we are facing. Journalists worldwide, especially independent ones, are not safe to operate and their rights are being violated all the time. The recent Assange trial - while a great outcome of him being released - still framed him as guilty which means journalists are not safe from future prosecutions. 
We signed this "Westminster Declaration" for free speech (I was one of the signatories) - and we need more awareness for this topic: https://efrat.substack.com/p/resisting-censorship-the-westminster
Nostr can help with a censorship-free platform, but issues of media storage and relays should be discussed and improved. 
I'd be privileged to participate in Michelle's panel.

**Comment by HeatherLarson** [comment]
I think we've just seen, with what is happening in Venezuela, the power of getting the story out to the world. If it's not Venezuela, it's Kansas in the middle of America. Or it's a global pandemic in 2020. Whatever it is, the story faces the chance it may be silenced. You won't find breaking news anymore on X like you do in real-time on Nostr. You will never see it again on any Meta platform. Now, we are seeing AI influence elections worldwide. We need a safe haven where journalism can live uncensored. Algorithms should have no power over the truth.

**Comment by SusieViolet** [comment]
Nostr represents a sustainable future for independent journalism, where freedom of speech and fair compensation can coexist. The discussion around independent journalism is vital, as independent journalists often exist only through great sacrifice. Recent statistics from the Oslo Freedom Forum show that 72% of the world lives under some form of authoritarian regime, while others live under the illusion of democracy. I've been battling the BBC since November 2023 to retract a misleading article claiming each bitcoin transaction uses a swimming pool's worth of water. Despite providing concrete evidence, they have not yet issued a retraction. Most of their bitcoin coverage has been negative, written by journalists with no background in tech or finance. 

Independent journalists often work out of moral obligation, but this business model is not viable. As a result, we get poorly researched, biased news, where governments and corporations are intertwined. This feeds back into the financial challenges journalists face today. There's no adequate system to compensate journalists fairly, whether for routine articles or deeply researched investigations. 

Platforms like Nostr, which enable direct micropayments, will solve this problem.

**Comment by exfrog** [comment]
@sexylibrarian please confirm who will be on this panel with you!

**Comment by sexylibrarian** [comment]
So far, here’s the panel line up:Susie Violet WardJournalist, Co-founder and Head of Mining & Energy at Bitcoin Policy UKMichelle Information Scientist, Journalist, Founder & CEO of MyLibrarian and the Independent Voice / In the StacksStill waiting to hear if Efrat Fenigson will be coming.It’s fine if it’s just Susie and I, however, we may add 1-2 more as things come together this week.I will have a few slides. When do you need them by?Cheers,Michelle ZSent from my iPadOn Aug 17, 2024, at 5:47 AM, exfrog ***@***.***> wrote:﻿
@sexylibrarian please confirm who will be on this panel with you!

**Comment by sexylibrarian** [comment]
Hello again, feel free to add Susie Violet Ward as a presenter for this panel talk. Efrat may not be able to travel. A high-level overview of the talk is Old Journalism, New Journalism, Old Money, New Money. And I’ll have one slide to share. Cheers—MichZ Sent from my iPadOn Aug 17, 2024, at 12:07 PM, Michelle Zaffino ***@***.***> wrote:﻿So far, here’s the panel line up:Susie Violet WardJournalist, Co-founder and Head of Mining & Energy at Bitcoin Policy UKMichelle Information Scientist, Journalist, Founder & CEO of MyLibrarian and the Independent Voice / In the StacksStill waiting to hear if Efrat Fenigson will be coming.It’s fine if it’s just Susie and I, however, we may add 1-2 more as things come together this week.I will have a few slides. When do you need them by?Cheers,Michelle ZSent from my iPadOn Aug 17, 2024, at 5:47 AM, exfrog ***@***.***> wrote:﻿
@sexylibrarian please confirm who will be on this panel with you!

**Comment by exfrog** [comment]
At this point we won't update the GitHub entry but anyone you want on stage
is fine. Max 4 mics

**Comment by source-c** [comment]
Hey! We just added #87 and wanted to ask here - this might be cool to bring these both topics up in a coherent way as a discussion. At least I see there are 4 mics and a lot of subjects that might interfere when it is natural talk of such great people. What do you think @exfrog @sexylibrarian ? Thank you.

**Comment by exfrog** [comment]
@source-c i replied in your issue
