### ISSUE TITLE
Mostro: A censorship-resistant peer-to-peer lightning platform on top of Nostr 

### ISSUE THREAD

**Issue by grunch** [nostrworld/nostriga#54]
# Description
### What is this talk about? Give us as many details as possible. 

Mostro, an avant-garde project, unfolds a revolutionary approach to facilitate Bitcoin transactions through the Lightning Network. The project addresses the growing demand for buying and selling Bitcoin without compromising personal data, introducing a groundbreaking solution for peer-to-peer exchanges.

Mostro manages communications on top of Nostr, creating a decentralized platform without a single point of failure. This design enhances resistance to censorship compared to other existing options.

### What would an attendee learn from this talk?

How it all started from [@lnp2pbot](https://lnp2pbot.com/) to Mostro, overview of how Mostro works under the hood and a NIP proposal to create a big liquidity pool for p2p platforms.

### Relevant Links

https://mostro.network/
https://mostro.network/messages/
https://github.com/MostroP2P/mostro
https://github.com/nostr-protocol/nips/pull/1331

# About the Speaker
### Social Links
Nostr - https://nostr.com/npub1qqqqqqqx2tj99mng5qgc07cgezv5jm95dj636x4qsq7svwkwmwnse3rfkq
Github - https://github.com/grunch 
Twitter - https://twitter.com/negrunch

# Talk Details
### Length of Talk
25 minutes
### Preferred Day/Time Slot 
No preference

**Comment by alltheseas** [comment]
Would love to learn more about p2p on nostr
