### ISSUE TITLE
nostroots: nostr and real life social networks

### ISSUE THREAD

**Issue by guaka** [nostrworld/nostriga#56]
Trustroots is a real life social network of travelers and hosts (think couchsurfing(tm)) that offer couches. Founded in 2014, 111k+ members now.

In 2022 it was clear we shouldn't continue as a centralized platform. nostr wasn't ready yet, we looked at ActivityPub (federated so no real solution) and Secure Scuttlebutt (hardly usable).

In 2024 we became serious about moving Trustroots onto nostr and our effort is supported by OpenSats.

https://github.com/Trustroots/nostr-map, simple nostr geo chat app we built:
    - issues we encountered developing on nostr and thoughts about solutions
    - our next steps

We'll also talk about what we are working now and later:
- how to do trustroots trust on nostr, NIP-77 https://github.com/nostr-protocol/nips/pull/1208
- notes that aren't 100% public nor 100% private?
          * only available to trusted or limited circles?
          * e.g. profile and other sensitive data
- connect existing and new projects, e.g.
        * [hitchwiki](https://hitchwiki.org/) (which we run) with active community of hitchhikers
        * bootstrap [rideshares.org](https://www.rideshares.org/) as a nostr based rideshare app
        * bikesurf.org, bike sharing platform in Berlin and other cities
        * triphopping.com, for those who want to travel freely and spontaneously
        * your project?
- problems/solutions around private keys for 100k+ users?

## About the Speakers
We cofounded trustroots in 2014.

### Social Links
Nostr https://iris.to/npub1lt6a968lk4h6yqduqnxcha628cudulgy8xk607c4xyxn6d6w6kcsmgp8hj
Github https://github.com/Trustroots/nostroots https://github.com/Trustroots/nostr-map
Website https://www.trustroots.org/

## Workshop Details
Length of workshop: ~45 mins

### Preferred Day/Time Slot 
* Ideally not before 11:00.

**Comment by itstomekk** [comment]
Oh nice, you run Hitchwiki and Trustroots!? And it's moving to Nostr?
Great, can't wait for that workshop!

**Comment by guaka** [comment]
Important questions:

- What nostr apps would be a culture fit for trustroots? https://github.com/Trustroots/nostroots/issues/26
- Useful nostr based chat apps? https://github.com/Trustroots/nostroots/issues/25
