### ISSUE TITLE
Saving Private Nostr

### ISSUE THREAD

**Issue by jb55** [nostrworld/nostriga#6]
# Description
### What is this talk about? Give us as many details as possible. 

There have been many different proposals for making nostr more private. The goal of this talk is to explore some of these ideas and how they compare with each other, as well as a more general question: what does a private nostr look like? Does a private nostr even make sense given how the public the protocol is to its core. Can we protect against data leaks? Can we make it harder to propagate notes? etc.

### What would an attendee learn from this talk?

What are the different approaches for achieving a more privacy nostr, from tame to extreme measures.

### Is there anything folks should read up on before they attend this talk?

I created a tracking issue in the NIPS repo for this topic:

- https://github.com/nostr-protocol/nips/issues/1183

### Relevant Links

# About the Speaker
### Social Links
Nostr: jb55@jb55.com
Github: jb55
Twitter: @jb55
Website: jb55.com, damus.io

# Talk Details
### Length of Talk
30 mins ?
### Preferred Day/Time Slot
Flexible

**Comment by space-shell** [comment]
Do we have a date set for this event? Thanks.

**Comment by miketwenty1** [comment]
@space-shell this will be either on August 22, or 23rd.

**Comment by miketwenty1** [comment]
@jb55 Congratulations we've accepted this talk. Stay tuned for scheduling.
