### ISSUE TITLE
Evolving Digital Life on Nostr 

### ISSUE THREAD

**Issue by cypherperro** [nostrworld/nostriga#60]
# Description
### What is this panel discussion about? Please give us as many details as possible.

The [closed](https://situational-awareness.ai/) vs. [open](https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/) source AI debate is heating up.

Nostr offers a unique and valuable environment in which to evolve open and decentralized artificial intelligence. It’s the only region of the web with authenticity (via signed messages), WoT rankings, and the potential for [market/value rank](https://hivemind.vc/howtodisruptgoogle/). 
Nostr can thus serve as a backend dataset for a next generation answer engine that could replace google search (similar to how Reddit and other data sets are the current back end for Perplexity and other answer engines). 

What are the best routes to evolve this digital life? 

- Are Nostr fine tunes enough? E.g. [Unleashed Chat](https://unleashed.chat/app/chat), [Nous Research](https://nousresearch.com/) but focused on Nostr/Lightning
- Training base models only on Nostr Evolutionary Optimization via Model Merging (see [Sakana AI](https://sakana.ai/evolutionary-model-merge/))
- Focusing on agent coordination instead of new models (e.g. see [Open Agents](https://openagents.com/), [DVMs](https://github.com/nostr-protocol/nips/blob/master/90.md))

What are the best ways to fund this work? What sorts of products, end use cases, and businesses could this enable? 

- Personal Agents / Information curators (e.g. [Kagi](https://kagi.com/), [Unleashed Chat](https://unleashed.chat/app/chat))
- Marketplaces for agents/orchestration (e.g. [Open Agents](https://openagents.com/)) 
- Data opportunities? (e.g. [Fewsats](https://www.fewsats.com/), [DVMs](https://github.com/nostr-protocol/nips/blob/master/90.md))

Reaching Synthetic Data Loops:

- First rounds of training are largely RLHF, including incentivizing populating Nostr with high quality data via users with high trust rank (e.g. [Project Alexandria](https://habla.news/a/naddr1qvzqqqr4gupzphtxf40yq9jr82xdd8cqtts5szqyx5tcndvaukhsvfmduetr85ceqqxnzde38yerqdpexsmnyvekwpld9e))
- Next rounds of training via reinforcement learning from bots (synthetic data loops, i.e. the Alpha Go Moment for LLMs) 

### Is there anything folks should read up on before they attend this talk?

- https://situational-awareness.ai
- https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/
- https://hivemind.vc/ai/ 
- https://hivemind.vc/howtodisruptgoogle/
- https://sakana.ai/llm-squared/

# About the panelists

- @pablof7z npub1l2vyh47mk2p0qlsku7hg0vn29faehy9hy34ygaclpn66ukqp3afqutajft
- Stu Bowman npub1lunaq893u4hmtpvqxpk8hfmtkqmm7ggutdtnc4hyuux2skr4ttcqr827lj
- @dtdannen npub1mgvwnpsqgrem7jfcwm7pdvdfz2h95mm04r23t8pau2uzxwsdnpgs0gpdjc
- Moderator: @cypherperro (Max) npub18lzls4f6h46n43revlzvg6x06z8geww7uudhncfdttdtypduqnfsagugm3

# Panel Discussion Details
### Length of the panel discussion
~40 mins 

### Preferred Day/Time Slot 
Afternoon either day 

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by dtdannen** [comment]
This looks interesting and I'd be glad to participate.
