### ISSUE TITLE
Growing a New Web

### ISSUE THREAD

**Issue by cypherperro** [nostrworld/nostriga#61]
# Description
### What is this panel discussion about? Please give us as many details as possible. 

The legacy web faces multiple growing problems: 
- It’s drowning in AI spam. There’s no way to distinguish fact from friction. 
- There are multiple centralized choke points - e.g. DNS 
- It’s not designed for agents or payments (i.e. it’s not machine payable) 

How a New Nostr Web could solve these problems:
- Authenticity via signatures on every message and Web of Trust (WoT) 
- Alternatives to DNS for discovering services
- Machine payable by default (DVMs?)

What technical architecture(s) could achieve this?
- [Nostr Web Services](https://www.nobsbitcoin.com/introducing-nostr-web-services-nws/) 
- [Nostr Web Hosting](https://github.com/nostr-protocol/nips/pull/811/files) 
- Others ?

How to transfer, build, and curate information on this new Nostr web? 
- Incentivized data collection/curation (e.g. [Project Alexandria](https://habla.news/a/naddr1qvzqqqr4gupzphtxf40yq9jr82xdd8cqtts5szqyx5tcndvaukhsvfmduetr85ceqqxnzde38yerqdpexsmnyvekwpld9e))

### Relevant Links
See above 

# About the panelist

- @pablof7z npub1l2vyh47mk2p0qlsku7hg0vn29faehy9hy34ygaclpn66ukqp3afqutajft
- Stu Bowman npub1lunaq893u4hmtpvqxpk8hfmtkqmm7ggutdtnc4hyuux2skr4ttcqr827lj
- A 3rd: perhaps @callebtc, @brugeman, or others? 
- Moderator: @cypherperro (Max) npub18lzls4f6h46n43revlzvg6x06z8geww7uudhncfdttdtypduqnfsagugm3

# Panel Discussion Details
### Length of the panel discussion
~40 mins 
### Preferred Day/Time Slot 
Afternoon either day 

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by roytheholographicuniverse** [comment]
I will fly to Riga to see this talk!
