### ISSUE TITLE
Secret key (nsec) management techniques, tools review and improvement suggestions

### ISSUE THREAD

**Issue by GregTonoski** [nostrworld/nostriga#64]
# Description
### What is this talk about?
About secret Nostr keys management techniques, tools review and improvement suggestions; challenges faced by users, typical user issues.
### What would an attendee learn from this talk?
Dos and don'ts of secret key management.
### Is there anything folks should read up on before they attend this talk?
No.
### Relevant Links
None.

# About the Speaker
### Social Links
npub133s4w0s6gnpxs00yxmtsteejsu0jetqem7r54peza9avhx60raqsla52tn
[Github ](https://github.com/GregTonoski/)

# Talk Details
### Length of Talk
30 min.
### Preferred Day/Time Slot 
No preference.

**Comment by itstomekk** [comment]
Good idea!

**Comment by derekross** [comment]
Would be good for Nostr 101 track
