### ISSUE TITLE
Funding Nostr

### ISSUE THREAD

**Issue by Marce198** [nostrworld/nostriga#65]
# Description
Funding Nostr Development

# About the panelist
Alex Li, HRF, npub1szpa7cypmyd59083qs3pte9lez22lzfu6pl2guhgqx7q09x68y6qquh3td
ODELL, Ten31, npub1qny3tkh0acurzla8x3zy4nhrjz5zd8l9sy9jys09umwng00manysew95gx
Dread, Open Sats, npub1qqqqqq0u2gj96tdfvqymdqn739k4s0h9rzdwyegfmalv28j7a5ssh5ntu2
Max Webster, Hivemind, npub18lzls4f6h46n43revlzvg6x06z8geww7uudhncfdttdtypduqnfsagugm3

**Comment by exfrog** [comment]
Dread is out, do we have another?
