### ISSUE TITLE
We need more albinos on Nostr!

### ISSUE THREAD

**Issue by Marce198** [nostrworld/nostriga#67]
Is needing more women on nostr like saying we need more albinos in bitcoin? What do these female nostriches/bitcoiners think about this?

Mir Liponi npub1ydxytlu95vwpn0m3pzn507nma8x5472u043pupcgpj3dvcamglfql6rlcw
Marce npub1y67n93njx27lzmg9ua37ce7csvq4awvl6ynfqffzfssvdn7mq9vqlhq62h

**Comment by itstomekk** [comment]
we need more left-handed!

**Comment by itstomekk** [comment]
ahh sorry im not female why do i comment
