### ISSUE TITLE
Difficult cryptography fixes everything by Fiatjaf

### ISSUE THREAD

**Issue by alltheseas** [nostrworld/nostriga#7]
# Description
### What is this talk about? Give us as many details as possible. 
Generally this is about fiatjaf asessing the inevitable/already occured failure of lightning network, and talking multi-sig on nostr. Fiatjaf also will talk about his love of social media. 

### What would an attendee learn from this talk?
Attendees will learn a lot about drivechains, Dilma, and how to troll others.

### Is there anything folks should read up on before they attend this talk?
Attendees should familiarize themselves with the ATProtcol documentation https://atproto.com/docs and web5 DID spec https://github.com/TBD54566975/web5-spec

### Relevant Links

# About the Speaker
### Social Links
Nostr https://njump.me/npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6
Github  github.com/fiatjaf
Twitter https://twitter.com/fiatjaf
Website https://fiatjaf.com/nostr.html

# Talk Details
### Length of Talk 

30 minutes
### Preferred Day/Time Slot 

it cannot be before noon or after 1230 pm
Fiatjaf must also be supplied with picanha

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by fiatjaf** [comment]
Please proceed assuming this is a joke submission. I cannot travel to Riga departing from Bahia since the flight would have to do a dangerous BA-Riga landing.

**Comment by alltheseas** [comment]
@fiatjaf what would it take to get you to Riga? I will organize it on your behalf. 

Air ticket, room & board? How many sats?

**Comment by exfrog** [comment]
this would be great, lol
