### ISSUE TITLE
Bringing superpowers to bitcoin apps and wallets with Nostr Wallet Connect

### ISSUE THREAD

**Issue by stackingsaunter** [nostrworld/nostriga#72]
I know agenda is already full, but I'd love to do a talk on Nostr Wallet Connect If somehow you guys manage to fit it

# Description
![image](https://github.com/user-attachments/assets/9eeb904d-57f2-4ab7-8e6a-ccaa3e97e246)

### What is this talk about? Give us as many details as possible. 
This is an intro to what is Nostr Wallet Connect, how it works and a showcase (demos, recordings) of a few apps that use it to create unique payment experiences.

### What would an attendee learn from this talk?
- How NWC works
- New possibilities of programmable payments that NWC brings to wallet and app builders
- A glimpse of the future of NWC

### Is there anything folks should read up on before they attend this talk?
No :)

### Relevant Links
[Slide deck](https://www.figma.com/proto/9dVRBKfRitg4mkSgsfd0GN/NWC-deck?page-id=0%3A1&node-id=2303-193&viewport=4179%2C6926%2C0.53&t=wq6ux2YRYegi5xKv-1&scaling=contain&content-scaling=fixed&starting-point-node-id=2303%3A193)

# About the Speaker
### Social Links
[Nostr](https://primal.net/profile)
[Github ](https://github.com/stackingsaunter)
[Twitter](https://x.com/StackingSaunter)

# Talk Details

### Length of Talk
30m 

### Preferred Day/Time Slot 
Any time, preferably afternoon

**Comment by itstomekk** [comment]
I'M ALL EARS
