### ISSUE TITLE
Rebuilding Fountain's Social Features on Nostr

### ISSUE THREAD

**Issue by MerryOscar** [nostrworld/nostriga#78]
# Description

[Fountain](https://fountain.fm) is a podcast app that uses payments as a discovery signal for what content is worth listening to.

Previously we had built our own internal social graph, profiles, and commenting system to power these social discovery features.

Over the past few months we've rebuilt the social features from the ground up using nostr - and I thought it would be useful to share our experience doing this so that other developers get an insight into some of the challenges in migrating to nostr rather than starting with it from scratch.

Some of the things I'd like to cover:

- reasons and benefits of switching to nostr
- why open podcasting should adopt nostr as the social layer
- [NIP-73 External Content IDs](https://github.com/nostr-protocol/nips/blob/master/73.md)
- fountains new audio feed architecture
- the challenges of migrating existing profile data to nostr
- future plans for podcast discovery on nostr

# About the Speaker
Oscar Merry
Nostr - https://primal.net/p/npub1unmftuzmkpdjxyj4en8r63cm34uuvjn9hnxqz3nz6fls7l5jzzfqtvd0j2
Twitter - https://x.com/MerryOscar

# Talk Details
Length of Talk: 30 mins (flexible)
Preferred Day/Time Slot: (flexible)

**Comment by Sebastix** [comment]
Looking forward to this talk to see how to nostrify a current application :)
@MerryOscar I've send you a Nostr DM for a Testflight invite, but got no reply (yet).

For my keynote https://github.com/nostrworld/nostriga/issues/49 I would like to highlight the 'POSSE' features which Fountain has build with Nostr :)
