### ISSUE TITLE
Globalization of Nostr

### ISSUE THREAD

**Issue by tyiu** [nostrworld/nostriga#8]
# Description

### What is this talk about? Give us as many details as possible. 
What is globalization and why do we need to globalize Nostr?

Many people have a more favourable bias towards others who speak the same language, have a similar culture, or have similar ideas. These biases lead to an unhealthy echo chamber and alienates others who are in a minority or are not well-represented. People residing in countries that have strong protections for freedom of expression currently dominate Nostr, and our clients and tools reflect that. Many clients are English-first or English-only, and other languages seem to be second-class citizens. There are people who do not speak English or live in non-English speaking countries who do not have the same rights to freedom of expression, and they do not have easy access to freedom technology that cater well to them. They need Nostr just as much or even more.

### What would an attendee learn from this talk?
An attendee would learn about how to include people who are different from them into their community and discussions.
A builder would learn about how to think about designing their Nostr software in a global-first way.

### Is there anything folks should read up on before they attend this talk?
No.

# About the Speaker

### Social Links

Nostr
https://njump.me/tyiu.xyz

GitHub
https://github.com/tyiu

Website
https://tyiu.xyz/

# Talk Details

### Length of Talk
30 minutes.

### Preferred Day/Time Slot
Anytime.

**Comment by waterblower** [comment]
This one please
